* <2017-09-18 Mon> Shanghai
** 13:25 HongQiao Airport
KA813	2017年9月18日(星期一)	SHA 13:25 HKG 15:55			2小时30分钟       运营航空公司： Cathay Dragon

连接时间：2小时55分钟

CX111	2017年9月18日(星期一)	HKG 18:50 SYD 06:10 +1			9小时20分钟       运营航空公司： Cathay Pacific

* <2017-09-19 Tue> Sydney
** 06:10
Arrival at Ariport

Take City Circle via Museum to Circular Quay, 去四季酒店寄存行李后去悉尼歌剧院。

** 悉尼歌剧院(Sydney Opera House) 4.7/5分

一小时汉语观光游每天于9:30、11:00、13:00、14:30 开始。餐厅开放及演出时间各不相同；圣诞节、耶稣受难日关闭。
地址：Bennelong Point, Sydney NSW 2000
悉尼歌剧院和海港大桥是澳大利亚的象征。悉尼歌剧院是公认的20世纪世界七大奇迹之一，是悉尼最容易被认出的建筑，它白色的外表，建在海港上的贝壳般的雕塑体，象飘浮在空中的散开的花瓣，多年来一直令人们叹为观止。它内设音乐厅、歌剧场、戏剧场、儿童剧场和一个摄影场，每个月甚至每星期这里都要举行拍卖会、音乐会和其它各种活动，是悉尼最受欢迎的地方。

** 悉尼鱼市(Sydney Fish Market) 4.3/5分
从歌剧院步行45分钟到达， @12：00午餐  地址：Blackwattle Bay，Corner Pyrmont Bridge Road and Bank Street，Sydney，New South Wales，2009

周一-周四7:00-16:00，周五-周日7:00-17:00，圣诞节关闭，每个餐馆营业时间不尽相同。

悉尼鱼市是南半球最大的海鲜市场，在这里你将亲身经历鱼市的色彩与喧闹。鱼市于清晨 5:30开市，此时海鲜买家已进入市场，在当天的海鲜被拍卖前进行验货。你有机会进行一次幕后之旅，并能观看所有的活动。

** 悉尼水族馆
从鱼市步行17分钟到达，  @14:00  地址：1-5 Wheat Road, Sydney, New South Wales, 2000

周一周四9:30-18:00（17:00停止入馆）周五-周日、节假日9:30-18:00（17:00停止入馆），开放时间会根据季节变化有所调整，具体以官网为主。

悉尼水族馆是全世界最大、最壮观的水族馆之一，位于达令港东部，主体建筑在达令港水面下。这里的通道长达百米，两边都是圆弧形的透明玻璃，真正与海洋生物面对面！水族馆展出了来自澳大利亚各大海域的水生生物，比如鸭嘴兽、小丑鱼、小企鹅以及会变性的拿破仑鱼，许多海洋生物也只能在悉尼水族馆才看得到，比如大型纺锤状的儒艮！请预留至少一个半小时的时间参观。这里多个馆都根据澳大利亚海域来命名。

** 悉尼海港大桥
有兴致就去 地址：Sydney, New South Wales 2060
悉尼海港大桥是早期悉尼的代表建筑，它像一道横贯海湾的长虹，巍峨俊秀，气势磅礴，与举世闻名的悉尼歌剧院隔海相望，成为悉尼的象征。悉尼人对这座大桥崇拜异常。被称为“衣架”的巨大钢结构拱形桥周身遍布的铆钉近600万个，而且都是手工加工而成。大桥将中央商务区与悉尼北部的商业区连接在一起。建桥的时间跨度长达8年，于1932年完工，耗资3200万澳元。悉尼足足用了60年才将这笔开支支付完毕

** Hotel Checkin
Four Seasons Hotel 2 nights HK$ 4477

* <2017-09-20 Wed> Sydney
** 蓝山国家公园
A、火车+686巴士
蓝山线（Blue Mountains Line），站台：4—15号，中央车站（Central）到卡通巴站（Katoomba），发车时间：07:21，抵达时间：09:23 ，109公里，行程：2小时02分钟；卡通巴站出来，沿主路往南走50米就是卡林顿酒店（The Carrington Hotel），在这里等候686路巴士。686路每天最早的三班车是 09:20 / 09:50 / 10:20（半小时一班），686路车是专跑蓝山景区的环行车，围着各景点转，按次收费，每上一次车是2澳元

B、悉尼到Katoomba 的火车票+ 蓝山当地循环巴士的车票
火车票请在火车站窗口购买
蓝山当地循环巴士有两家：一家是双层的红巴士 Explorer Link：一家是单层的咖啡巴士 Trolley Bus：绕行的时间与停点请查看官网信息。

** 达令港 晚餐
达令港（Darling Harbour）位于悉尼CBD的西部，聚集了各种休闲娱乐的场所，购物中心、酒吧、西餐厅、南半球最大的IMAX屏幕，晚上还会有一些街头表演。这里的晚上和白天感觉完全不同，一定要来这边过过夜生活。夜晚，除了灯光璀璨之外，最重要的是气氛，每周六晚上20：30会有音乐焰火表演，感觉超赞！在这里也可以慢慢地散步，欣赏被林立的高楼包围着的浪漫海港的美。所以一定要晚上去。
达令港附近有很多的高档西餐厅、酒吧和甜品店，牛排很好吃呢，是一个非常nice的约会地点，晚上可以看到很多二人细语、甜蜜的景象。
悉尼水族馆、海事博物馆和杜莎夫人蜡像馆，也都在走路范围内，可以顺道参观。拥有着超浪漫名字的达令港，如传说中一样，天空中都弥漫着爱的气息。

* <2017-09-21 Thu> Sydney->Cairns
Flight Cost: CNY 4598
** 11:00 Hotel Checkout

** 14:10 Arrive at 金斯福德史密斯机场T2
JQ958	澳大利亚-悉尼(金斯福德史密斯机场-T2航站楼)	澳大利亚-凯恩斯
(凯恩斯机场-T2航站楼)	2017-09-21 14:10	2017-09-21 17:20
** 17:20 Arrive at 凯恩斯国际机场T2
4.1公里， 打车去酒店
** Hotel Checkin 
Cairns Queenslander Hotel & Apartments 5 nights CNY 3928
** 凯恩斯夜市 Cairns Night Market

* <2017-09-22 Fri> Cairns
** 摩尔外堡礁 Moore Outer Reef
大堡礁(Great Barrier Reef) 4.5/5分

摩尔外堡礁位于澳大利亚的度假天堂凯恩斯。它是世界上规模最大、景色最美的生物活体珊瑚大堡礁群。摩尔外堡礁有数以万计的瑰丽海洋生物令人赞叹不已。有灵巧的小丑鱼尼莫，巨大但友好温顺的福寿鱼，可爱憨厚的大海龟，和色彩斑斓让人惊艳的珊瑚礁。

摩尔外堡礁海上平台的活动也很丰富，不会游泳的游客可以去海底观景站，或者乘坐玻璃底船、半潜水艇，这些项目都能让你透过玻璃观测水下世界。海底漫步需要戴上连接着空气输送管道的头盔，你在水下也能正常呼吸。在海洋水族缸可以触摸珊瑚，全封闭游泳池专为儿童而设，若预定了直升机体验，将从空中俯看到极为壮美的海景。心型礁和白沙天

* <2017-09-23 Sat>  Cairns
** 绿岛一天
绿岛(Green Island) 4.5/5分

交通： 大冒险号（Great Adventures）：有双体船定期前往绿岛，8:30、10:30和13:00从凯恩斯出发，12:00、14:30和16:30返回。大冒险号双体船往返船票69澳元起（免费使用岛上游泳池，乘坐玻璃底船观察珍奇珊瑚与丰富热带鱼群以及在绿岛餐厅上享用自助式餐佳肴。并提供多项自费行程可供选择，如海底漫步，直升飞机观光等）。

门票
1. 成人：88澳元，儿童：44澳元，家庭：220澳元
2, 浮潜158澳元/人、直升飞机169澳元/人（全程10分钟）、玻璃船18澳元/人

* <2017-09-24 Sun>  Cairns
** 雨林一天
库兰达热带雨林公园(Rainforestation Nature Park) 4.6/5分

1. 08:00 凯恩斯市区主要酒店车接出发，具体出发时间以出游凭证上的时间为准；
2. 08:30 乘坐库兰达观光火车，穿越雄伟的巴伦瀑布（Barron Falls);
3. 10:15 抵达之后，步行至巴士停车处，司机会在此等候您，巴士将送您到库兰达小镇上，这里距离最近的餐厅和公厕都只要五分钟步行时间；
4. 10:30 参观蝴蝶园(Australian Butterfly Sanctuary)，
5. 10:30 到达库兰达小镇中心，这里处处鸟语花香，到处洋溢一派宁静的热带小镇风光
6. 11:45 在库兰达蝴蝶园门口乘坐热带雨林接送车，前往热带雨林公园（建议提前10分钟到达上车点）;
7. 15:45 在热带雨林公园门口搭乘热带雨林接送车，前往库兰达Skyrail缆车站（Kuranda）, 到达后换乘Skyrail雨林缆车返回凯恩斯。
8. 17:15 您的接送巴士将在Skyrail缆车的最后一站史密斯菲尔德站（Smithfield）的Caravonica站台外等您，将带您返回凯恩斯市区酒店上车点。

* <2017-09-25 Mon>  Cairns
随意

* <2017-09-26 Tue> Cairns-->Sydney

** 05:00 Hotel Checkout 
** 07:10 凯恩斯国际机场T2
JQ953	澳大利亚-凯恩斯
(凯恩斯机场-T2航站楼)	澳大利亚-悉尼
(金斯福德史密斯机场-T2航站楼)	2017-09-26 07:10	2017-09-26 10:05	经济舱
** 10:05 金斯福德史密斯机场T2

** 21:55 KINGSFORD SMITH T1
CX138	2017年9月26日(星期二)	
SYD 21:55 HKG 05:15 +1			9小时20分钟
   运营航空公司： Cathay Pacific

连接时间：4小时45分钟
KA858	2017年9月27日(星期三)	
HKG 10:00 SHA 12:20			2小时20分钟
   运营航空公司： Cathay Dragon

* <2017-09-27 Wed> Shanghai
** 12:20 SHANGHAI HONGQIAO INTL T1
