* <2017-09-18 Mon> Shanghai
** 13:25 HongQiao Airport
KA813	2017年9月18日(星期一)	
SHA 13:25 HKG 15:55			2小时30分钟
   运营航空公司： Cathay Dragon

连接时间：2小时55分钟
CX111	2017年9月18日(星期一)	
HKG 18:50 SYD 06:10 +1			9小时20分钟
   运营航空公司： Cathay Pacific

* <2017-09-19 Tue> Sydney
** 06:10
Arrival at Ariport
** Hotel Checkin
Four Seasons Hotel 2 nights HK$ 4477
** 悉尼歌剧院(Sydney Opera House) 4.7/5分
一小时汉语观光游每天于9:30、11:00、13:00、14:30 开始。餐厅开放及演出时间各不相同；圣诞节、耶稣受难日关闭。
地址：Bennelong Point, Sydney NSW 2000
悉尼歌剧院和海港大桥是澳大利亚的象征。悉尼歌剧院是公认的20世纪世界七大奇迹之一，是悉尼最容易被认出的建筑，它白色的外表，建在海港上的贝壳般的雕塑体，象飘浮在空中的散开的花瓣，多年来一直令人们叹为观止。它内设音乐厅、歌剧场、戏剧场、儿童剧场和一个摄影场，每个月甚至每星期这里都要举行拍卖会、音乐会和其它各种活动，是悉尼最受欢迎的地方。
** 悉尼鱼市(Sydney Fish Market) 4.3/5分
周一-周四7:00-16:00，周五-周日7:00-17:00，圣诞节关闭，每个餐馆营业时间不尽相同。
地址：Blackwattle Bay，Corner Pyrmont Bridge Road and Bank Street，Sydney，New South Wales，2009
悉尼鱼市是南半球最大的海鲜市场，在这里你将亲身经历鱼市的色彩与喧闹。鱼市于清晨 5:30开市，此时海鲜买家已进入市场，在当天的海鲜被拍卖前进行验货。你有机会进行一次幕后之旅，并能观看所有的活动。
** 悉尼海港大桥
全天开放。
地址：Sydney, New South Wales 2060
悉尼海港大桥是早期悉尼的代表建筑，它像一道横贯海湾的长虹，巍峨俊秀，气势磅礴，与举世闻名的悉尼歌剧院隔海相望，成为悉尼的象征。悉尼人对这座大桥崇拜异常。被称为“衣架”的巨大钢结构拱形桥周身遍布的铆钉近600万个，而且都是手工加工而成。大桥将中央商务区与悉尼北部的商业区连接在一起。建桥的时间跨度长达8年，于1932年完工，耗资3200万澳元。悉尼足足用了60年才将这笔开支支付完毕
** 悉尼水族馆
周一周四9:30-18:00（17:00停止入馆）周五-周日、节假日9:30-18:00（17:00停止入馆），开放时间会根据季节变化有所调整，具体以官网为主。
地址：1-5 Wheat Road, Sydney, New South Wales, 2000
悉尼水族馆是全世界最大、最壮观的水族馆之一，位于达令港东部，主体建筑在达令港水面下。这里的通道长达百米，两边都是圆弧形的透明玻璃，真正与海洋生物面对面！水族馆展出了来自澳大利亚各大海域的水生生物，比如鸭嘴兽、小丑鱼、小企鹅以及会变性的拿破仑鱼，许多海洋生物也只能在悉尼水族馆才看得到，比如大型纺锤状的儒艮！请预留至少一个半小时的时间参观。这里多个馆都根据澳大利亚海域来命名。

* <2017-09-20 Wed> Sydney
** 蓝山国家公园
A、火车+686巴士
蓝山线（Blue Mountains Line），站台：4—15号，中央车站（Central）到卡通巴站（Katoomba），发车时间：07:21，抵达时间：09:23 ，109公里，行程：2小时02分钟；卡通巴站出来，沿主路往南走50米就是卡林顿酒店（The Carrington Hotel），在这里等候686路巴士。686路每天最早的三班车是 09:20 / 09:50 / 10:20（半小时一班），686路车是专跑蓝山景区的环行车，围着各景点转，按次收费，每上一次车是2澳元

B、悉尼到Katoomba 的火车票+ 蓝山当地循环巴士的车票
火车票请在火车站窗口购买
蓝山当地循环巴士有两家：一家是双层的红巴士 Explorer Link：一家是单层的咖啡巴士 Trolley Bus：绕行的时间与停点请查看官网信息。

* <2017-09-21 Thu> Sydney->Cairns
Flight Cost: CNY 4598
** 11:00 Hotel Checkout

** 14:10 Arrive at 金斯福德史密斯机场T2
1	JQ958	澳大利亚-悉尼
(金斯福德史密斯机场-T2航站楼)	澳大利亚-凯恩斯
(凯恩斯机场-T2航站楼)	2017-09-21 14:10	2017-09-21 17:20
** 17:20 Arrive at 凯恩斯国际机场T2

** Hotel Checkin 
Cairns Queenslander Hotel & Apartments 5 nights CNY 3928

* <2017-09-22 Fri> Cairns
** 出海浮潜一天（可选帆船，如果想钓鱼是不是也可以归到同一天）
大堡礁(Great Barrier Reef) 4.5/5分

* <2017-09-23 Sat>  Cairns
** 绿岛一天
绿岛(Green Island) 4.5/5分

* <2017-09-24 Sun>  Cairns
** 雨林一天
库兰达热带雨林公园(Rainforestation Nature Park) 4.6/5分

* <2017-09-25 Mon>  Cairns
** 坐海上飞机一天
心型礁和白沙天

* <2017-09-26 Tue> Cairns-->Sydney

** 05:00 Hotel Checkout 
** 07:10 凯恩斯国际机场T2
JQ953	澳大利亚-凯恩斯
(凯恩斯机场-T2航站楼)	澳大利亚-悉尼
(金斯福德史密斯机场-T2航站楼)	2017-09-26 07:10	2017-09-26 10:05	经济舱
** 10:05 金斯福德史密斯机场T2
** 21:55 KINGSFORD SMITH T1

* <2017-09-27 Wed> Shanghai
** 12:20 SHANGHAI HONGQIAO INTL T1
