#+PAGEID: 1825545337
#+VERSION: 30
#+STARTUP: align
#+OPTIONS: toc:1
#+TITLE: IMG Design

* Consolidation Model Definition
Maintain IMG: T-code SIMGH; IMG Structure: Real-Time Consolidation 
** (Text Node) Create Consolidation Foundation View
This step is not mandatory(in 1709). As there are 2 default foundations are delivered. 

In this customizing activity, you create consolidation foundation views that will be the basis for all the consolidation tasks in a consolidation model.

Foundation views are HANA views which provide the real-time data source to consolidation. Among them, the most significant one is the financial journal foundation view. Additional consolidation views will be generated by the Real-Time Consolidation modeling tool based on the foundation views given.

Foundation views can be CDS view or HANA Calculation view. CDS views are created using ABAP Development Tools (ADT); HANA Calculation views are created using the graphical modeling features of the SAP HANA Modeler. In both cases, you must have SAP HANA Studio(Eclipse based) installed on your laptop.

_@Grace, If possible, provide a download link of SAP HANA Studio._

Fields in foundation views are protocoled. Some fields are mandatory and with fixed names, while others can be freely added. Bellow is an example of streamlined foundation view for company consolidation. It projects fields from universal journal(ACDOCA).
| Field Name | Field Description                   | Usage                                       |
|------------+-------------------------------------+---------------------------------------------|
| RCLNT      | SAP Client                          | Mandatory                                   |
| RLDNR      | Ledger in General Ledger Accounting | Mandatory: for drill-through                |
| GJAHR      | Local Fiscal Year                   | Mandatory: for drill-through                |
| RBUKRS     | Company Code                        | Mandatory: for drill-through                |
| BELNR      | Accounting Document Number          | Mandatory: for drill-through                |
| RCOMP      | Company                             | Mandatory if consolidation is on company    |
| RASSC      | Trading Partner                     | Mandatory if consolidation is on company    |
| BUDAT      | Posting Date                        | Mandatory: for fiscal year period alignment |
| KTOPL      | Local Chart of Accounts             | Mandatory                                   |
| RACCT      | Local Account Number                | Mandatory                                   |
| RMVCT      | Transaction Type                    | Mandatory                                   |
| RWCUR      | Transaction Currency Key            | Optional                                    |
| RHCUR      | Company Code Currency Key           | Mandatory                                   |
| WSL        | Amount in Transaction Currency      | Optional                                    |
| HSL        | Amount in Company Code Currency     | Mandatory                                   |
| TIMESTAMP  | Timestamp                           | Mandatory: for data cut-off                 |

In general, the foundation view must achieve the following objectives:
1. Project consolidation-relevant fields from the financial journal table.
2. Do the necessary data filtering.

Example foundation views are provided for your reference. You can copy them to your own, and adjust them according to your own requirements. The 4 foundation views are categorized into "ACTUAL" and "PLAN" data categories, which can be directly used.
| Data Category | Type | View              | Description                             |
|---------------+------+-------------------+-----------------------------------------|
| ACTUAL        | CDS  | P_FOUNDATIONA     | Consolidation Foundation View on ACDOCA |
| ACTUAL        | Calc | RTC_C_FOUNDATIONA | Consolidation Foundation View on ACDOCA |
| PLAN          | CDS  | P_FOUNDATIONP     | Consolidation Foundation View on ACDOCP |
| PLAN          | Calc | RTC_C_FOUNDATIONP | Consolidation Foundation View on ACDOCP |

~The HANA Calculation Views are in package: sap.erp.sfin.rtc. The modeling tool will automatically copy them to your own HANA package if you use them.~

| Attribute             | Value              | Comments                      |
|-----------------------+--------------------+-------------------------------|
| ASAP Road-map ID       | 152                | Design data acquisition        |
| Mandatory/Optional    | Mandatory activity |                               |
| Critical/Non-Critical | Critical           | This activity is fundamental |

** Financial Accounting Preparation
*** (Text Node) Prepare for Consolidation
In this Customizing activity, you must finish consolidation preparation tasks for required master data such as G/L Chart of Accounts, company, and  profit center.

Perform any necessary consolidation preparation IMG activities in Customizing for Financial Accounting (New) under Consolidation Preparation (New).

*Note*: You do not need to perform the activities under Consolidation Preparation (New) -> General Specifications -> Transaction Types, because Real-Time Consolidation has its own settings for transaction type.

*** Generate Fiscal Year Calendar
In this Customizing activity, you generate fiscal year calendar data for the alignment between local fiscal year variants and group fiscal year variants. The program determines for a fiscal year variant the fiscal calendar data, such as the fiscal year, period and quarters.

You have configured the local fiscal year variants and group fiscal year variants. If you use the same fiscal year variant for the local and group accounts, then this step is not necessary.

Input the group fiscal year variant and the target fiscal year in which you want map it to the calendar dates. You can also define the offset of the target fiscal year, so that you can generate data for multiple fiscal years.

Example: If you want to convert fiscal year variant '24' and the fiscal years from 2016 to 2020, you enter '4' in the Offset after Fiscal Year field.

~You don't have to manually execute this step, as it is automatically checked and executed during package initialization if you use Data Release Monitor.~

| Attribute             | Value             | Comments                                         |
|-----------------------+-------------------+--------------------------------------------------|
| ASAP Road-map ID       | 203               | Establish Master Data                            |
| Mandatory/Optional    | Optional activity | Only needed if local and group FSV are different |
| Critical/Non-Critical | Critical          |                                                  |

** Define Consolidation Dimension                                       
In this Customizing activity, you define consolidation dimensions. A consolidation dimension defines on which account assignment field (or fields) in the universal journal (table ACDOCA) you want to perform consolidation.

SAP delivers the following default dimensions:
| Dimension | Description   | Assignment Field(s)  | Partner Assignment Field(s) |
|-----------+---------------+----------------------+-----------------------------|
|       100 | Company       | RCOMP                | RASSC                       |
|       200 | Segment       | SEGMENT              | PSEGMENT                    |
|       500 | Cost Center   | (KOKRS,RCNTR,RBUKRS) | (KOKRS,SCNTR,PBUKRS)        |
|       600 | Profit Center | (KOKRS, PRCTR)       | (KOKRS, PPRCTR)             |

You can define your own dimensions in your customer namespace (starting with Y, Z, or 9). Ensure the assignment fields exist in both ACDOCA and ACDOCC.

*TCode*: RTCCMD

*Maintenance View*: VC_RTC_MODEL_DIM

| Attribute             | Value             | Comments                                   |
|-----------------------+-------------------+--------------------------------------------|
| ASAP Roadmap ID       | 203               | Establish Master Data                      |
| Mandatory/Optional    | Optional activity | Default dimensions cover most of the cases |
| Critical/Non-Critical | Critical          |                                            |
                            
** Create Consolidation Entity                                         
*** (Text Node)Generate Consolidation Entities Automatically
In this Customizing activity, you generate consolidation entities based on existing master data. An entity can be a company, a segment, a profit center, or a cost center.

Consolidation entities can be created manually or generated based on existing master data.

SAP recommends that you first use this activity to generate your entities, then adjust the generated entities in the Customizing activity Create Consolidation Entities Manually.

Run the Generate Entities from Consolidation Dimension Definition report (RTC_AUTO_PUMP_ENTITIES) using transaction SA38. Select one consolidation dimension, and choose Execute. The report creates all entities for you based on existing master data.

Note that you can only use this report to generate entities based on SAP-delivered consolidation dimensions ('100', '200', '500', and '600'). For your self-defined dimensions, you must write an ABAP report to automatically generate your entities. You can base your custom report on the Generate Entities from Consolidation Dimension Definition report (RTC_AUTO_PUMP_ENTITIES).

You can also create consolidation entities manually, or maintain entities created in this activity, in the Customizing activity Create Consolidation Entities Manually.

*** Maintain Consolidation Entities
In this Customizing activity, you can manually create or maintain consolidation entities.

You can write an ABAP report to generate entities automatically based on your existing master data. SAP recommends that you first generate your entities using the Generate Entities from Consolidation Dimension Definition program (RTC_AUTO_PUMP_ENTITIES), then use this activity to adjust them.

For more information on generating consolidation entities using the Generate Entities from Consolidation Dimension Definition program, see the Customizing activity Generate Consolidation Entities.

Select a consolidation dimension, and maintain your entities. You can also maintain BPC-required attributes for each entity.

*TCode*: RTCENT

*Maintenance View*: VC_RTC_MODEL_DIM

| Attribute             | Value              | Comments                    |
|-----------------------+--------------------+-----------------------------|
| ASAP Roadmap ID       | 202                | Establish Company Structure |
| Mandatory/Optional    | Mandatory activity |                             |
| Critical/Non-Critical | Critical           |                             |

** Define Version Related Fields
In this section, you define version-related fields.

Version-related fields are characteristic fields that are combined together to form a consolidation version that reflects a consolidation purpose. 

There are 3 version-related fields:
1. Data Category
2. Consolidation Ledger
3. Variant

A version is then comprised to this form "Data Category/Consolidation Ledger/Variant". There are different configurations on each of the version fields. The combination of the 3 fields represents a unique configuration set that can also achieve reusebility. 

Details are explained in each version field.

*** (Text Node) Data Category
Data Category is the first version field that is used to differentiate different data sources. Simple Upload and Additional Financial Data are entered into data categories. You can use data category to isolate the consolidation source data for deferent purpose. For example, you might define categories for plan, actual, or simulation data, and so on.

*Notice*: Data Category here is a different concept with BPC Category. BPC Category is BPC's version concept, while Data Category is part of RTC's version concept and only used to isolate the source data. However, a RTC consolidation version can have a one-on-one map with BPC Category.

You can define data categories in RTC modeling tool(RTCMD). A RTC model can contain more than one data categories, and each data category can be are assigned with different foundation views. SAP delivers the following default data category templates:
1. Actual: contains foundation views(both CDS and Calculation view) on ACDOCA;
2. Plan: contains foundation views(both CDS and Calculation view) on ACDOCP.
You can choose copy from template to ease your modeling creation.  

For details please refer =Define Consolidation Model=.

| Attribute             | Value              | Comments              |
|-----------------------+--------------------+-----------------------|
| ASAP Roadmap ID       | 203                | Establish Master Data |
| Mandatory/Optional    | Mandatory activity |                       |
| Critical/Non-Critical | Critical           |                       |

*** Consolidation Ledger
In this Customizing activity, you define consolidation ledgers.

Consolidation ledger is the second version field which has consolidation methods(rules) be assigned. For example, you assign different currency translation methods to different ledgers. It acts as a media for sharing consolidation rules among different consolidation versions.

*Notice*: consolidation ledger is different with accounting ledgers. 

*TCode*: RTCLM

*Maintenance View*: VC_RTC_LEDGER

| Attribute             | Value              | Comments              |
|-----------------------+--------------------+-----------------------|
| ASAP Roadmap ID       | 203                | Establish Master Data |
| Mandatory/Optional    | Mandatory activity |                       |
| Critical/Non-Critical | Critical           |                       |

*** Variant
In this Customizing activity, you can define variants to further subdivide a set of consolidation results into versions.

Variant is the third version field. It allows the parallel consolidation of data using the same RTC data category and ledger. Customizations like exchange rate indicators are defined on variants. Besides, there are also attributes alone with variants like data release mode and CT options. 
1. Data Release Mode controls whether data release is required for the consolidation version. If you choose "Data Release is not Required", then the versions contain this variant won't be shown in the Data Release Cockpit.
2. Currency Translation Option controls whether CT is needed before data release. 

Under the combination of "RTC Data Category" and "Consolidation Ledger", you may want to further differentiate the consolidation result set. For example, "Actual / 1L / 100" for legal disclosure, and "Actual / 1L / 200" for internal management reporting.

SAP delivers the following default variants which allow directly use:
1. 100: Data Release with LC and GC;
2. 200: No Data Release;
3. 300: Data Release with LC.

*TCode*: RTCVER

*Maintenance View*: V_RTC_VERSION

| Attribute             | Value              | Comments              |
|-----------------------+--------------------+-----------------------|
| ASAP Roadmap ID       | 203                | Establish Master Data |
| Mandatory/Optional    | Mandatory activity |                       |
| Critical/Non-Critical | Critical           |                       |

** Define Consolidation Model.
In this Customizing activity, you create a Real-Time Consolidation model.

In Real-Time Consolidation (RTC), a model is used to bundle all the definitions, customizations, and consolidated results into an integrated consolidation context. It consists of two parts: one on the SAP S/4HANA Real-Time Consolidation (RTC) side, and one on the SAP Business Planning & Consolidation (BPC) side.

~You can also create a model without BPC integration. You can use non-BPC integrated model for group reporting, or integrated with other consolidation systems. Then you don't need to do the modeling on BPC part.~

In this activity, you must first generate Consolidation Views in RTC side.

=Activities=
1. Create a new model by entering a six-character-long model name and choosing Create Model.
2. In the popup dialog, you decide whether the model is integrated with BPC. If it is for BPC integration, then you also need to assign a default flow type. 
3. Enter a description.
4. In the Basic tab, enter a dimension, a group Chart-of-Accounts, and a group Fiscal Year Variant. If all entities and the group share the same Chart-of-Accounts or Fiscal Year Variant, click the checkbox after them. 
5. In the Data Source tab, you define data categories. Click the first button(Copy from Template), in the popup dialog, choose template "Actual", and click OK button to confirm.
6. In the Version tab, you define consolidation versions. Click the add button, maintain the 3 version fields, give a description, and click OK. If it is for BPC integration, then you also need to map a BPC category to each consolidation version. 
7. In the Consolidation View tab, you generate consolidation views. 

By now, you can not activate the model as the BPC part is still not finished yet. Record the view name with suffix "_BPCUNION". Later you will create a BW virtual provider, on which you should assign the view. More details can be found in section "BPC Integration".

After you finished modeling on BPC side, you come back here, input the BPC environment and BPC model name and activate the model.

~BPC categories can be set up for different types of data that you want to track. For example, you can have a category for actual data, one for budget data, another for forecast data, and so on. Multiple categories can also be defined to store versions of the same type of data, such as 'BUDGETV1', 'BUDGETV2', and so on.A BPC category therefore maps directly to a version in Real-Time Consolidation, which is comprised of a combination of three version-related fields. To integrate with BPC, there must be one-one mapping between BPC categories and Real-Time Consolidation versions.~

*TCode*: RTCMD

*SOBJ*: RTCA

| Attribute             | Value              | Comments                       |
|-----------------------+--------------------+--------------------------------|
| ASAP Roadmap ID       | 105                | Define functions and processes |
| Mandatory/Optional    | Mandatory activity |                                |
| Critical/Non-Critical | Critical           |                                |

** Define Consolidation Document type
In this section, you set up the consolidation document types. Consolidation document types are used to differentiate types of consolidation documents generated by different consolidation tasks.

In a document type, you can assign a posting level, define balance check behavior, and assign a number range interval. After model activation, there are 4 default document types generated:
| Doc. Type | Description              |
|-----------+--------------------------|
|        00 | Flexible Upload          |
|        01 | Currency Translation     |
|        02 | Data Release             |
|        03 | BPC Write-back           |
|        04 | Defer from Prior Periods |
~There is also a default number range interval '00' be generated for all years. The interval is from 1000000000 to 1999999999.~

| Attribute             | Value              | Comments                       |
|-----------------------+--------------------+--------------------------------|
| ASAP Roadmap ID       | 105                | Define functions and processes |
| Mandatory/Optional    | Mandatory activity |                                |
| Critical/Non-Critical | Critical           |                                |

*** Define Number Range Intervals
In this Customizing activity, you define number range intervals for a Real-Time Consolidation (RTC) model. You can define different number range intervals for different consolidation tasks.

Enter the model in the initial screen, and choose Change intervals. Add your intervals with a unique name and year combination, and define the From No. and To Number of the range.

*Note*: Do not check the External Assignment check-box, as this is currently not supported in Real-Time Consolidation.

*TCode*: RTCNR

| Attribute             | Value              | Comments            |
|-----------------------+--------------------+---------------------|
| ASAP Roadmap ID       | 250                | Define Number Range |
| Mandatory/Optional    | Mandatory activity |                     |
| Critical/Non-Critical | Critical           |                     |

*** Maintain Document Types
In this Customizing activity, you maintain the document types for Real-Time Consolidation.

A document type categories consolidation documents by combining configurations like: posting level, balance check, business transaction type, and a number range interval.  

In case the posting level is set to 09 Currency Translation, the Offset Items tab is shown. You can assign balance sheet and income statement offset items. This is useful if during Currency Translation, an entry posted to balance sheet and income statement accounts leads to an imbalance in the financial statements. Then the offset items are used to keep balance. 

*TCode*: RTCDT

*SOBJ*: RTCA


* BPC Integration
** (Text Node) Essential Steps
This section gives the essential steps you need for the integration with BPC. 

You are using the SAP BusinessObjects Planning and Consolidation 10.1 embedded version. The BPC instance must be in the same instance with S4HANA and Real-time Consolidation. 

1. Create BW Info-Objects for consolidation master data dimension. You can activate the pre-delivered contents in the BW InfoArea "/ERP/RTC".
2. Maintain BPC Property Extension. BPC needs some specific properties on the dimensions of account, transaction type, BPC category, and Entity.
3. Create a Virtual Info-Provider. You create a virtual info-provider based on the generated BPC view with suffix "_BPCUNION", and map the view fields to the correct Info-Objects. You also need assign a write-back class on the virtual info-provider.
4. Create a Ownership Cube and an Exchange Rate Cube(if you want run currency translation in BPC). Refer [[http://help-legacy.sap.com/saphelp_bopacnw101/helpdata/EN/4c/3382b535c520d4e10000000a42189b/content.htm?frameset=/EN/4c/33873135c520d4e10000000a42189b/frameset.htm&current_toc=/en/82/f51cf12cfc48c58975b9b5e6fba9aa/plain.htm&node_id=143][BPC Help Doc]].
5. Create a BPC environment and a consolidation model.

| Attribute             | Value              | Comments                      |
|-----------------------+--------------------+-------------------------------|
| ASAP Roadmap ID       | 105                | Define function and processes |
| Mandatory/Optional    | Mandatory activity |                               |
| Critical/Non-Critical | Critical           |                               |

** (Text Node) Create BW Info-Objects
In this Customizing activity, you create BW Info-Objects for the characteristic fields of the generated consolidation view.

You need HANA Studio installed with BW Modeling add-on.

You can mix use virtual Info-Objects and physical Info-Objects in the same virtual provider. It is recommended to use virtual Info-Objects as you don't have to replicate the data from your transaction systems. 

To ease your modeling work, standard BW virtual InfoObjects and their corresponding SAP HANA calculation views are delivered. To use them, you need activate the BW contents in the InfoArea '/ERP/RTC'.

Activate the standard delivered InfoObjects, or build your own InfoObjects (virtual or physical).

| Attribute             | Value              | Comments                |
|-----------------------+--------------------+-------------------------|
| ASAP Roadmap ID       | 152                | Design Data acquisition |
| Mandatory/Optional    | Mandatory activity |                         |
| Critical/Non-Critical | Critical           |                         |

** BPC Extended Property Maintenance
*** Extend GL Account Properties for BPC:
In this Customizing activity, you extend the G/L account properties for integration with SAP Business Planning & Consolidation (BPC).

This extension table is for properties of the BPC account dimension (A).

For each G/L account, defined per chart of accounts, you define the following dimension properties:
1. DIMLIST
2. ELIMACC
3. ENABLEJNR
4. TYPELIM
5. Exchange rate type
6. Account type

Additionally, you can maintain the following G/L account properties:
1. G/L Account Type
2. Account Group
3. Mark for Deletion
4. Language-Dependent Short Text and Long Text


*TCode*: RTCGLA

*Maintenance View*: V_RTC_EXT_SKA1

*** Extend Transaction Type for BPC:
In this Customizing activity, you can extend transaction types for integration between Real-Time Consolidation (RTC) and SAP Business Planning & Consolidation (BPC).

For each transaction type, you assign a balance carry-forward transaction type and define the following dimension properties:
1. FLOW_TYPE
2. DIMLIST
3. ENABLEJNR

*TCode*: RTCTTP

*Maintenance View*: V_RTC_EXT_T856

*** Extend BPC Category:
In this Customizing activity, you can extend the Integrated Business Planning for SAP Simple Finance (IBP) data category properties for integration between Real-Time Consolidation (RTC) and SAP Business Planning & Consolidation (BPC).

For each BPC category, you define the following dimension properties:
1. FX_DIFFERENCE_ONLY
2. FX_SOURCE_CATEGORY
3. DATA_SUBMIT
4. Opening category
5. Opening year
6. Opening period
7. RATE_CATEGORY
8. RATE_YEAR
9. RATE_PERIOD
10. OWN_CATEGORY
11. OWN_YEAR
12. OWN_PERIOD
13. DIMLIST
14. ENABLEJNR

*TCode*: RTCBCT

*Maintenance View*: FCOMV_CATEGORY_C

*** Extend Entity Properties for BPC
In this Customizing activity, you can extend the consolidation entity attributes for integration between Real-Time Consolidation (RTC) and SAP Business Planning & Consolidation (BPC).

For each entity, you define the following dimension properties:
1. CONTROL_LEVEL
2. CTRL_CURRENCY_NOT_LC
3. DIMLIST
4. ELIM
5. ENABLEJNR
6. FX_TYPE

*TCode*: RTCENT

** (Text Node) Create a Virtual Info-Provider and Aggregation Level
In this Customizing activity, you create a BW Virtual Provider on the generated consolidation view with suffix "_BPCUNION".

You create virtual provider using RSA1. 

1. Create a virtual provider based on a SAP HANA Model, and assign the generated BPC view(with suffix "_BPCUNION") and its package.
2. Assign CL_RTC_ACDOCC_IPROV_WRITABLE to the write interface.
3. Assign SAP HANA View fields, and assign each field with an Info-Object.
4. Save and Activate the virtual provider.
5. Create an aggregation level on the virtual provider.

** (Text Node) Create a Ownership Cube and Exchange Rate Cube
In this Customizing activity, you create a ownership cube and exchange rate cube. 

The exchange rate cube is not necessary if you don't need run currency translation in BPC. 

Refer [[http://help-legacy.sap.com/saphelp_bopacnw101/helpdata/EN/4c/3382b535c520d4e10000000a42189b/content.htm?frameset=/EN/4c/33873135c520d4e10000000a42189b/frameset.htm&current_toc=/en/82/f51cf12cfc48c58975b9b5e6fba9aa/plain.htm&node_id=143][BPC Help Doc]].

** (Text Node) Create a BPC Consolidation Model
In this Customizing activity, you create a BPC consolidation model in an BPC environment. 

Refer [[http://help-legacy.sap.com/saphelp_bopacnw101/helpdata/EN/4c/2a3088a33157d8e10000000a42189c/content.htm?frameset=/EN/4c/3382b535c520d4e10000000a42189b/frameset.htm&current_toc=/en/82/f51cf12cfc48c58975b9b5e6fba9aa/plain.htm&node_id=107&show_children=false][BPC Help Doc]]

** Finalize and Activate Real-time Consolidation Model
In this Customizing activity, you complete the creation and activation of the Real-Time Consolidation model, after you have set up the integration with BPC.

After you successfully define your BPC model, you return to the Real-Time Consolidation modeling tool (transaction RTCMD) in this activity to do the following additional settings:
1. Enter a descriptive name for the model in the Description field.
2. In the BPC Integration tab, assign the BPC consolidation environment and model. 
3. Activate the  Real-time Consolidation Model.

*Note* that all the settings between RTC and BPC will be checked for the model consistency. These settings include dimension types, fiscal year variant, chart of accounts, and so on. If there is any inconsistency, it prohibit you to activate the model.

** (Text Node) Define Consolidation Group
In this Customizing activity, you must define the required consolidation groups and entities.

Consolidation groups and entities form the consolidation hierarchy which is a fundamental structure to control how consolidation tasks run. Real-Time Consolidation (RTC) uses the existing consolidation hierarchy of SAP Business Planning & Consolidation (BPC), which is built upon the ownership cube and supports time-dependency.

Open the BPC web client, select your consolidation environment, and choose Administration -> Dimensions. Select your group dimension (/ERP/GROUP is chosen by default). You can now maintain your consolidation group hierarchy.

To add consolidation entities to the groups, choose Consolidation -> Ownership Manager, and choose the category, group, and fiscal year/period. Add your consolidation entities under each group node.

The consolidation hierarchy defined in BPC can be accessed in RTC for its currency translation. Only the hierarchy structure and group currency information are used in RTC; fields such as Consolidation Method, Percent Consolidation, Percent Control, and Percent Ownership are only relevant for BPC.


| Attribute             | Value              | Comments                    |
|-----------------------+--------------------+-----------------------------|
| ASAP Roadmap ID       | 202                | Establish Company Structure |
| Mandatory/Optional    | Mandatory activity |                             |
| Critical/Non-Critical | Critical           |                             |
 
** Assign Document Types for BPC Write-back
In this Customizing activity, you assign the document types used when writing back results to the consolidation journal (ACDOCC). By default, document type '03' will be inserted under a model when it is first activated.  

When BPC writes back the consolidated results to ACDOCC, the document types are automatically determined by the combination of the following:
1. Real-Time Consolidation model
2. BPC category
3. Transaction type
4. Audit trail

For each required combination of model, category, transaction type, and audit trail specification, assign a document type to be used during the writing back of data to ACDOCC.

=Example=

| Model | Category | Transaction Type | Audit Trail | Document Type |
|-------+----------+------------------+-------------+---------------|
| MOD1  | FINAL    |              200 | A           | F1            |
| MOD2  |          |                  |             | T1            |
| MOD3  | PRELIM   |                  |             | T2            |
| MOD3  | PRELIM   |              100 |             | T3            |

If a field is empty, the assigned document type will apply to all values of that field.

The rows of the table determine the document types as follows:
1. If the model is MOD1, the category is FINAL, the transaction type is 200, and the audit trail is A, then the document type used will be F1.
2. If the model is MOD2, then the document type used will be T1.
3. If the model is MOD3, and the category is PRELIM, then the document type used will be T2.
4. If the model is MOD3, the category is PRELIM, and the transaction type is 100, then the document type used will be F1.

*TCode*: RTCWB

*Maintenance View*: V_RTC_MODWB

| Attribute             | Value              | Comments            |
|-----------------------+--------------------+---------------------|
| ASAP Roadmap ID       | 204                | Establish Functions |
| Mandatory/Optional    | Mandatory activity |                     |
| Critical/Non-Critical | Critical           |                     |
** (Text Node) Enhance Write-back to SAP S/4HANA
In this Customizing activity, you set up a customized write-back class to receive the consolidation documents from SAP Business Planning & Consolidation (BPC) and write them into the consolidation journal (ACDOCC).

The standard write-back class CL_RTC_ACDOCC_IPROV_WRITABLE is available. However, if it doesn't fulfil your requirements, then you can copy this class and implement your own logic.

Use the Class Builder transaction (SE24) to create a class that includes the following three interfaces (which are available in the class CL_RTC_ACDOCC_IPROV_WRITABLE):
1. IF_RSDRV_RPROV_WRITABLE
2. IF_RSDRV_RPROV_LOCK_NOSID
3. IF_RSDRV_VPROV_LOC_NOSID_QUERY

Implement the write-back logic contained in the method WRITE_DATA of interface IF_RSDRV_RPROV_WRITABLE.

There are three main logics in the method WRITE_DATA:
1. Map field values from the VirtualProvider to table fields.
2. Modify table fields' values.
3. Post document to ACDOCC.

| Attribute             | Value              | Comments         |
|-----------------------+--------------------+------------------|
| ASAP Roadmap ID       | 151                | Design Interface |
| Mandatory/Optional    | Mandatory activity |                  |
| Critical/Non-Critical | Critical           |                  |


* Currency Translation
** (Text Node) RTC Currency Translation
In this section, you set up the currency translation(CT) for Real-Time Consolidation (RTC). Currency translation in RTC pushes all the translation logic into SAP HANA, which promises better performance and can achieve on-the-fly run translation.

You define translation methods under a consolidation model. Each translation method contains multiple translation entries. After activation, ABAP-Management-DB-Procedure(AMDP) is generated. These AMDP methods can be consumed by all possible applications.

You can define multiple translation methods for a model. The translation methods are then assigned to consolidation ledger and entities, or the combination.

The exchange rates should be maintained before you run currency translation. RTC CT reuses the rates table(TCUR*) as the rate source. 

There could be rounding differences during translation. You can define rounding methods to deal with the differences. 

** (Text Node) Define Currency and Exchange Rate Types
In this Customizing activity, you can define the currency and exchange rate types.

You can re-use existing exchange rate types or define new exchange rate types for your currency translation. You then define translation ratios and exchange rates for each exchange rate type.

Perform all necessary currency and exchange rate type definition in the activities in Customizing for SAP NetWeaver under General Settings -> Currencies.

** Exchange Rate Indicater
In this Customizing activity, you create and maintain exchange rate indicators and map them to exchange rate types.

Exchange rate indicators are created under variant. 

Create new entries as required, mapping exchange rate indicators to exchange rate types.

| Attribute             | Value              | Comments              |
|-----------------------+--------------------+-----------------------|
| ASAP Roadmap ID       | 203                | Establish Master Data |
| Mandatory/Optional    | Mandatory activity |                       |
| Critical/Non-Critical | Critical           |                       |

*TCode*: RTCER

*SOBJ*:  RTCA

** Define Rounding Methods
In this Customizing activity, you define the rounding methods used during currency translation in Real-Time Consolidation (RTC). Afterward, you assign these rounding methods to currency translation methods in Customizing for Financial Accounting (New) under Real-Time Consolidation -> Currency Translation Definition ->  Define Currency Translation Methods (transaction code RTCTM).

The translation of financial data can produce differences that are caused by rounding in the system. These rounding differences are not related to translation differences. Before rounding is done, the local currency amounts are checked based on rules such as the following (according to the specified rounding type), and after passing the check the rounding is performed for the group currency amounts (again based on the same rules):
1. Total assets = total liabilities and stockholder's equity (Selection 1 = Selection 2)
2. Total revenue + total expense = annual net income (Selection 1 + Selection 2 = 0)
3. Amortization/depreciation in the balance sheet = amortization/depreciation in the income statement

*Note*: The validation checks are only performed on the local currency amount; rounding differences in the group currency amount are not subjected to the same validation checks.

In order to calculate rounding differences, the system performs rounding checks. It then posts any differences it finds to the appropriate differential items. These differences are usually very small, because they are purely the result of the inaccuracies involved in rounding.

The Entry List tab displays a sequential list of the rounding entries. During runtime, these rounding entries are executed in sequence from top to bottom.

The Entry Detail tab allows you to edit the details of each rounding entry.

1. In the Entry List tab, insert one or more rounding entries.
2. For each entry, in the Entry Detail tab, add a short text description and specify the rounding type to be applied. The target amount field is always fixed as 'CONS_SL'.
3. You can add a selection to filter data by accounts and subitems.
4. In the Differential Items panel, specify the differential item field to be used to record rounding differences that may occur. Differential items must be members of the ranges specified in the selections for the rounding method.

** Define Currency Translation Methods
In this Customizing activity, you define the currency translation methods used in Real-Time Consolidation (RTC).

A translation method includes translation entries. Based on the definition, an ABAP class containing AMDP methods is created. At runtime, the system calls the generated AMDP methods, so that all the translation logic is pushed down to SAP HANA.

Translation methods are model-dependent. You can define multiple translation methods for a consolidation model, and assign them to different consolidation ledger and entity combination. 

1. In the translation method header, assign the following:
   1. document type for automatic posting during the translation run. The default document type "01" is given.
   2. reference exchange rate indicator
2. In the Entry tab, add one or more translation entries.
3. For each entry, add a selection to filter data by accounts and subitems.
4. Assign an exchange rate type and a currency translation key.
5. A currency translation key maps to a translation algorithm (for details, see "Define Translation Key").
6. In the Amount panel, you can choose which amount field is used as the source amount. The target amount is always fixed as 'CONS_SL'.
7. For differential amounts, you can assign a differential account and its subitems in which to record them.

*TCode*: RTCTM

*SOBJ*:  RTCA

| Attribute             | Value              | Comments              |
|-----------------------+--------------------+-----------------------|
| ASAP Roadmap ID       | 204                | Establish Functions   |
| Mandatory/Optional    | Mandatory activity | Main CT customization |
| Critical/Non-Critical | Non-Critical       |                       |

** Setting Target Group Currencies
This customizing activity is optional. If you are running a model with BPC integration, you can ignore it.

If you are running a model without BPC integration, then there is no group hierarchy data. In this case, when you run RTC CT, there should be target group currencies maintained before hand. And you can maintain the target group currencies here under each variant. 

If the target group currency is not maintained for a certain variant, you will run into error during data release with currency translation. 

*Maintenance View*: VC_RTC_MODEL_DIM

** Define Selection
In this Customizing activity, you define selections to further filter data in a consolidation view.

A selection is a model-dependent object. With it, you can add filter conditions on the fields of a consolidation view. The filter conditions are then compiled into a SQL WHERE clause, which can be applied during the running of consolidation tasks.

The filter conditions can be either direct selection options or based on sets. You can also combine multiple selections into a composite selection to form a more complex filter option.

In currency translation method definition, you can use selections for translation entries and rounding entries to select source data on fields like accounts, transition types, and other characteristics. In this case, you define reusable selections. 

1. Enter the model name and a name for your selection, and choose Create.
2. In the dialog box, choose the type of selection you wish to create.
3. Currently, only one base view is supported, which is the generated "_U" view.
4. Add a description for the selection.
5. In the Filter Columns tab, create filters by adding columns of the table to be filtered, and adding a filter expression. For example, you could create a filter for G/L account numbers within a specified range.
6. You must activate the selection to make it effective.

The Where String tab contains the SQL WHERE clause that is generated based on your chosen filter options.

*Note*: 
+ When entering a filter expression, From is mandatory, while To is optional.
+ Expressions of different fields are connected with the 'OR' operator.
+ In a single field, different from-to rows are connected with the 'AND' operator.
+ For Boolean values in your selection expression, use '!' for false, and 'X' for true.

*TCode*: RTCSEL

*SOBJ*:  RTCA

| Attribute             | Value              | Comments                          |
|-----------------------+--------------------+-----------------------------------|
| ASAP Roadmap ID       | 152                | Define data acquisition           |
| Mandatory/Optional    | Mandatory activity | You must define selections for CT |
| Critical/Non-Critical | Non-Critical       |                                   |

*** (Text Node)Reuse SETs 
If you already have your G/L accounting and subitem SETs, then you can re-use SETs as selection. Create selections with type "1" (based on SETs).

| Attribute             | Value             | Comments                          |
|-----------------------+-------------------+-----------------------------------|
| ASAP Roadmap ID       | 152               | Define data acquisition           |
| Mandatory/Optional    | Optional activity | You must define selections for CT |
| Critical/Non-Critical | Non-Critical      |                                   |

** Define Translation Keys
In this Customizing activity, you define the currency translation keys used in Real-Time Consolidation.

A translation key maps to a translation algorithm. In this activity, you can define your own translation algorithms using AMDP methods, and assign them with translation keys in your own namespace.

You have defined your own AMDP methods for currency translation.

Create new currency translation keys if required, assigning them with technical details of the AMDP methods you wish to map to them.

*TCode*: RTCCTK

*Maintenance View*: V_RTC_CT_CTRKY 

| Attribute             | Value             | Comments           |
|-----------------------+-------------------+--------------------|
| ASAP Roadmap ID       | 151               | Define enhancement |
| Mandatory/Optional    | Optional activity |                    |
| Critical/Non-Critical | Non-Critical      |                    |


* Data Release

** (Text Node) Data Release with Cut-off Timestamp
Data release stands for activities of transferring local financial data from local accountants to group accountants. Usually, data replications is needed to copy data from local systems to the consolidation system. However, in Real-Time Consolidation, the data replication step can be eliminated by only recording a timestamp, which typically represents the cut-off time. The timestamp is used to filter in the data before it from the journal table (ACDOCA/ACDOCC).

Each data release activity requires a Data Release Request to store the cut-off time. Local accountants are allowed to release multiple requests for each entity in each period, but only the latest approved request is taken into account. 

There are also different statues recorded on the data release request. For example: Initial, CT is ran, validation is passed, released, approved, rejected, deferred, and so on. Thus, business processes can be defined around data release requests. 

Data release requests can be divided to Periodic Release Request(PRR) and Adjustment Release Request(ARR). PRR happens recurrently for each entity and each period, and it is mandatory. ARR is raised occasionally, in case there is further adjustments after the PRR is processed. ARR can be deferred to next period, while PRR cannot. 

Please refer business catalog: SAP_FIN_BC_CONS_DATA_REL and SAP_FIN_BC_CONS_PREPARE for the related Fiori APPs.

** Assign Currency Translation Method
In this Customizing activity, you assign RTC CT methods to consolidation ledger and entity combinations. 

In case currency translation is needed before data release, you need to assign CT methods for the consolidation ledger and entity combinations. 

1. Choose a model and set method type to "CT";
2. Add assignment entries compose of a ledger, an entity, and a CT method. 

If you leave entity field empty, then it means the method is assigned to all entities. If afterward, you add an entry with entity, then the empty entity entry is ignored. 

*TCode*: RTCMA

*Maintenance View*: V_RTC_TASK_M
 
** Assign Validation Method
In this Customizing activity, you assign validation methods to consolidation ledger and entity combinations. 

Validation is needed before data release, you need to assign validation methods for the consolidation ledger and entity combinations. 

1. Choose a model and set method type to "VD";
2. Add assignment entries compose of a ledger, an entity, and a validation method. 

If you leave entity field empty, then it means the method is assigned to all entities. If afterward, you add an entry with entity, then the empty entity entry is ignored. 

*TCode*: RTCMA

*Maintenance View*: V_RTC_TASK_M

** Assign Financial Statement Version 
In this Customizing activity, you assign Financial Statement Version(FSV) to consolidation ledger and entity combinations. 

A FSV should be specified for Data Release Cockpit, otherwise, the report cannot be displayed in hierarchy format. Please refer IMG node: Financial Accounting (New)->General Ledger Accounting (New)->Master Data->G/L Accounts->Define Financial Statement Versions

1. Choose a model and set method type to "FSV";
2. Add assignment entries compose of a ledger, an entity, and a FSV. 

If you leave entity field empty, then it means the method is assigned to all entities. If afterward, you add an entry with entity, then the empty entity entry is ignored. 

*TCode*: RTCMA

*Maintenance View*: V_RTC_TASK_M


* TODO Business Add-ins

** BAdi for Core Posing API
The "Core posting API" is developed using AMDP(ABAP Managed DB Procedure). All the up-level applications will call the core posting API to save data into ACDOCC. You can define your BAdi implementation for core posting API if you have extend fields of ACDOCC and you want additional logic to be applied on this new fields.  

Developer: Chen, Lynn <lynn.chen02@sap.com>




