#+PAGEID: 1825545337
#+VERSION: 6
#+STARTUP: align
#+OPTIONS: toc:1
#+TITLE: IMG Design

* Consolidation Model
Here you define consolidation related master data and basic customizations.

** (Text Node) Create a Consolidation Foundation View
You need to create a CDS view in HANA Studio. The CDS view select consolidation raw data from existing tables. Currently, the main journal table is *ACDOCA*. The CDS view project fields from ACDOCA, and do Chart of Accounts mapping, fiscal year and period alignment, and necessary data filtering on company codes/ledgers. SAP also delivers an example consolidation foundation view: *C_RTC_ACDOCA*, you can copy it to your own namespaces and modify it to your own needs. 

** Define a Group Chart of Accounts
Reuse existing Chart of Accounts and G/L Accounting master data maintenance. 

Financial Accounting (New)-->General Ledger Accounting (New) -->Mater Data-->G/L Accounts

** Mapping Operational Chart of Accounts to Group Chart of Accounts
When create a local G/L account, assign the corresponding group account number. The underlying DB field is SKA1-BILKT

If time permits, RTC should develop a mapping application. You can do mapping like this:
| Local CoA | Local Account   | Group CoA | Group Account |
|-----------+-----------------+-----------+---------------|
| CACN      | 1001*           | CORP      |       1002000 |
| CAJP      | 2004001         | CORP      |       2004100 |
| CAGM      | 3003001,3003002 | CORP      |       3003000 |
| CAGM      | 4004001-4005999 | CORP      |       4004000 |

** Define Group Fiscal Year Variants
Reuse existing Fiscal Year Variants IMG nodes: Financial Accounting (New)-->Ledgers-->Fiscal Year and Posting Periods

** Generate Fiscal Year Calendar
Accounting team has a program to generate period level or day level granularity fiscal calendar. Maybe it is already existing in the IMG structure somewhere. But anyway we can create this node in our IMG structure. The program is: FINS_GENERATE_FISCAL_PERIOD . 

** Define Version Related Fields
Version related fields are characteristic fields which are combined together to form a consolidation version. A consolidation version reflects a consolidation purpose. From technique point of view, each version related field must be in ACDOCC, and it must be a char type field. 

You can define your own version related fields by extending ACDOCC with additional char type fields. But SAP standardly delievers following 3 version related fields: 
1. RTC Data Category
2. Consolidation Ledger
3. Version

*** RTC Data Category
Used to isolate the consolidation result data set for defferent purpose. Like "Actual", "Plan", "Simualtion".

Maintenance View: under development

*** Consolidation Ledger
A consolidation ledger can map to an accounting principle (US GAAP, IFAS, and so on). Ledger is useful when, for example, data in an extend ledger "1L" combined with the data in leading ledger "0L" can form a union data set to fulfill a specific accounting principle. Thus can reduce the data redundancy. 
 
Maintenance View: under developement

*** Version
~Version is a little confused here for its naming. As the version related fields combination is corresponding to the concept "Version", but one of them has its name as "Version". Maybe we should find a better name for it~

Under the combination of "RTC Data Category" and "Consolidation Ledger", you may want to further differentiate the consolidation result set. For example, "Actual / 1L / 100" for legal disclosure, and "Actual / 1L / 200" for internal management reporting. 

Maintenance View: V_RTC_VERSION

** Define a Consolidation Model.
Consolidation model combines all related customization together into an integral consolidation context. It mianly contains 2 parts: S/4 RTC side, and BPC side. 

You must first generated a consolidation area view in RTC side. Based on the consolidation area view, you create HANA calculation view, and then the BW composite infor-provider so that then you can do BPC model defination. More details on how to set BPC consolidation model can be found in section "BPC Integration".

After you successfully define your BPC model, you come back here to do following settings:
1. Assign BPC environment and model name.
2. Define BPC data categories, and mapping them to RTC version fields combinations.
3. Assign currency translation method if "Currency Translation in S4H" is checked. 
4. Do checks and validations, if all settings are correct, then you can activate the consolidation model.

SAP delievers a standard model "SCOMPL" for your reference. You can copy and adjust it to your needs.
 
*** Create a RTC Consolidation Model
You enter a model name with 6 char long, and click the button "New". In the pop-up dialog screen, you can assign the foundation view. Click "OK" will generate a consolidation area view for you. You can then use the consolidatoin area view to define your HANA calculation view and BW composite info-provider.

The Tcode "RTCMODEL" is still under development.

*** Assign BPC Environment and Model Name
In the tabstrip "Integration", you can assign a BPC environment name and a model name. The combination must be exist in BPC side. It will then read all the settings at BPC side, like: dimension field, fiscal year variant, chart of accounts, and so on. You just needn't do these settings again in RTC side.  

If "Currency Translation in S4H" is checked, you then assign a currency translation method. 

*** Define BPC Data Categroy and Map it to RTC Version Fields Combination
In the tabstrip "Version", you can add/delete a "BPC Data Category". When you add one, it must be a unqiue "BPC Data Categroy". You then choose each version field a value, the value combination should be unique too.

** (Text Node) Define Consolidation Group and Unit
You go to BPC's web console, choose your consolidation environment, goto Adminstration-->Dimensions, select your group dimension (/ERP/GROUP by default). You maintain your consolidation group hierarchy.

You then goto Consolidation-->Ownership Manager, choose the category, group, and Fiscal year/Period. You can then add your consolidation entities under each group node.

The consolidation hierarchy defined in BPC can be accessed in RTC for its currency translation (if "Currency Translation in RTC" is set). Only the hierarchy structure and group currency information is used, other like "Consolidation Method", "Percent Consolidation", "Percent Control", and "Percent Ownership" is only relevent for BPC.  


* Currency Translation
You define translation methods under a consolidation model. You can define multiple translation methods for a model, howerver, currently you can only have one working translation method for each model. 

** Define Selection
A =Selection= is a reusable object which defines a filtered data set based on a view or a table. It combines a base view or table and a filter defination which could be either SETs, Selecti Options, or HRF expression. The output artifact could be a "SQL Where-like" string, a table function, or a CDS view.

The TCODE "RTCSEL" is under development.

** Exchange Rate Indicator
A mapping with exchange rate type.

The Tcode "RTCERI" is done.

** Define Currency Translation Methods
Translation Methods includes translation entries and rounding entries. Based on them, an AMDP class will be generated. 

The Tcode "RTCTM" is under development.

*** Translation Entry
Translation entry combines a =Selection=, an exchange rate indicator, a translation key which points a translation algorithm, and a pair of differential items with their subitems.

The Tcode "RTCTE" is under development.

*** Rounding Entry 
Contains 1 or 2 =Selections= to do rounding check and rounding difference processing. 

The Tcode "RTCRE" is under development.


** Define Translation Key
A translation key is mapping to a translation algorithm. Here user can define his own translation algorithm using AMDP method, and assign it with a translation key in its own namespace. 

SAP delivers 8 standard translation keys. 

A maintenance view of the mapping between translation key and the algorithm should be maintained.


* BPC Integration
Here describe the details steps you should do for the integration with BPC. 

** BPC Extent Property Maintenance
You Maintenance following values for the BPC integration:

*** Extent Company Code Properties for BPC: 
Maintenance View: V_RTC_EXT_CEPC

*** Extent Company Properties for BPC:
Maintenance View: V_RTC_EXT_T880

*** Extent Cost Center Properties for BPC:
Maintenance View: V_RTC_EXT_SEGM

*** Extent Segment Properties for BPC:
Maintenance View: V_RTC_EXT_SEGM

*** Extent GL Account Properties for BPC:
Maintenance View: V_RTC_EXT_SKA1

*** Extent Business Area Properties for BPC:
Maintenance View: V_RTC_EXT_TGSBK


** (Text Node) Create HANA Calculation Views
You create a FACT HANA calculation view based the consolidation area view that are genereated during RTC modeling. You should also create master data HANA views to expose you master data. 

By default, SAP has delivered following standard master data HANA calculation views for your reference. They are all under HANA package: sap.erp.sfin.rtc

| Calc View             | Description                                           |
|-----------------------+-------------------------------------------------------|
| RTC_C_ACDOCA          | Fact View based on ACDOCA                             |
| RTC_C_SCOMPL          | Fact View based on the cons area view of model SCOMPL |
| RTC_BUSINESSAREA_T880 | Attribute View of Business Area                       |
| RTC_COSTCENTER_CSKS   | Attribute View of Cost Center                         |
| RTC_PROFITCENTER_CEPC | Attribute View of Profit Center                       |
| RTC_SEGMENT_SEGM      | Attribute View of Segment                             |

** (Text Node) Create BW Info-objects and Info-Provider
You need to create virtual info-objects to mapping the master data HANA views. You then create a real-time cube with the same fields of the FACT HANA calculation view. Then union the Real-time cube with the fact view through a composite provider.

SAP has delivered following BW contents for your reference:
| BW Objects    | Description                              |
|---------------+------------------------------------------|
| /ERP/RTC_RT01 | Real-time cube according to RTC_C_ACDOCA |
| /ERP/RTC_CP01 | Composite Provider on RTC_C_ACDOCA       |
| /ERP/RTC_AL01 | Aggregation Level on /ERP/RTC_CP01       |
| /ERP/RTC_RT02 | Real-time cube according to RTC_C_SCOMPL |
| /ERP/RTC_CP02 | Composite Provider on RTC_C_SCOMPL       |
| /ERP/RTC_AL02 | Aggregation Level on /ERP/RTC_CP01       |

** (Text Node) Write-back to S/4
If you want to write-back the consolidated results to S/4, then you have to use an ABAP write-back class and a BW virtual provider. 

SAP has delivered following objects for your reference:
| BW/ABAP Objects              | Description                                                |
|------------------------------+------------------------------------------------------------|
| CL_RTC_ACDOCC_IPROV_WRITABLE | Write-back class to post consolidation journals to  ACDOCC |
| /ERP/RTC_VP01                | BW Virtual Provider                                        |
  
