#+PAGEID: 1825545337
#+VERSION: 29
#+STARTUP: align
#+OPTIONS: toc:1
#+TITLE: IMG Design

* Consolidation Model
Here you define consolidation related master data and basic customizations.

** (Text Node) Create Consolidation Foundation View
You need to create a HANA calculation view in HANA Studio. The calculation view is based on ACDOCA, and is mainly used to
1. Project consolidastion relevent fields from ACDOCA;
2. +Join group Chart of Accounts;+
3. +Do fiscal year variant alignment;+
4. Do necessary data filtering on company code and ledger combinations.

SAP also delivers an example consolidation foundation view: *RTC_C_FOUNDATION*, you can copy it to your own namespace and adjust it to your own needs. 

| Attribute             | Value              | Comments                      |
|-----------------------+--------------------+-------------------------------|
| ASAP Roadmap ID       | 152                | Design data acquistion        |
| Mandatory/Optional    | Mandatory activity |                               |
| Critical/Non-Critical | Critical           | This activity is foundamental |

Developer: Zhou, Kaiyuan <kaiyuan.zhou@sap.com>

** Fiancial Accounting Prepartion
*** (Text Node) Define Group Chart of Accounts
In this Customizing activity, you must define a group chart of accounts for consolidation.

Please refer the IMG node:
Financial Accounting (New)-->General Ledger Accounting (New) -->Mater Data-->G/L Accounts

| Attribute             | Value              | Comments              |
|-----------------------+--------------------+-----------------------|
| ASAP Roadmap ID       | 203                | Establish Master Data |
| Mandatory/Optional    | Mandatory activity |                       |
| Critical/Non-Critical | Critical           |                       |

*** Assign Group Chart of Accts to (Transaction) Chart of Accts
Please fully refer: Enterprise Controlling-->Consolidation-->Integration:Preparation for Consolidation-->Preparation in the Sender System-->Preparations Related to All Consolidation Types-->Transaction Accounts: Assignment of Group Accounts-->Assign Group Chart of Accts of (Transation) Chart of Accts.

| Attribute             | Value              | Comments                    |
|-----------------------+--------------------+-----------------------------|
| ASAP Roadmap ID       | 202                | Establish Company Structure |
| Mandatory/Optional    | Mandatory activity |                             |
| Critical/Non-Critical | Critical           |                             |

*** (Text Node) Define Group Fiscal Year Variants
In this Customizing activity, you define a fiscal year variant for your consolidation model. You can of course re-use exiting one if it fulfill your requirement. 

Refer IMG nodes: Financial Accounting (New)-->Ledgers-->Fiscal Year and Posting Periods

| Attribute             | Value             | Comments              |
|-----------------------+-------------------+-----------------------|
| ASAP Roadmap ID       | 203               | Establish Master Data |
| Mandatory/Optional    | Optional activity |                       |
| Critical/Non-Critical | Critical          |                       |

*** (Text Node) Generate Fiscal Year Calendar
You generate fiscal year calendar data for the alignment between local fiscal year variant and group fiscal year variant. 

| Attribute             | Value             | Comments                                         |
|-----------------------+-------------------+--------------------------------------------------|
| ASAP Roadmap ID       | 203               | Establish Master Data                            |
| Mandatory/Optional    | Optional activity | Only needed if local and group fsv are different |
| Critical/Non-Critical | Critical          |                                                  |

Run report FINS_GENERATE_FISCAL_PERIOD using SA38. You use this report to maintain a fiscal calendar based on the fiscal year variant configuration. The report determines for a fiscal year variant the fiscal calendar data, such as the fiscal year, period and quarters with start and end dates for a calendar date. Those fiscal calendar data are used in analytical applications, such as the Trial Balance app, or in other Fiori apps that integrate the date picker component to let users choose the last fiscal year, period or quarter.

~Accounting team has a program to generate period level or day level granularity fiscal calendar. Maybe it is already existing in the IMG structure somewhere. But anyway we can create this node in our IMG structure. The program is: FINS_GENERATE_FISCAL_PERIOD.~ 

Developer: Zhou, Kaiyuan <kaiyuan.zhou@sap.com>

** Define Consolidation Dimension                                       
In this Customizing activity, you define consolidation dimensions. A consolidation dimension defines on which account assignment field(or fields) in ACDOCA you want to do consolidation. For example, Dimension =100= is for company consolidation. It has one account assignment field =RCOMP= and one partner account assignment field =RASSC=. 

SAP delivers 6 default dimensions, they are:
| Dimension | Description | (Partner)Assignment Field(s)              |
|-----------+-------------+-------------------------------------------|
|       100 | Company     | RCOMP:RASSC                               |
|       500 | Cost Center | (KOKRS,RCNTR,RBUKRS):(KOKRS,SCNTR,PBUKRS) |

You can define your own dimnsions in customer namespace(Start with Y, Z, 9). You should make sure the assignment fields should exist in both ACDOCA and ACDOCC. 

*TCode*: RTCCMD

*Maintenance View*: VC_RTC_MODEL_DIM

| Attribute             | Value             | Comments                                   |
|-----------------------+-------------------+--------------------------------------------|
| ASAP Roadmap ID       | 203               | Establish Master Data                      |
| Mandatory/Optional    | Optional activity | Default dimensions cover most of the cases |
| Critical/Non-Critical | Critical          |                                            |

** +(Text Node) Map Company Code to Company+
In this Customizing activity, you map company codes to companies if you want run a company consolidation. 

| Attribute             | Value             | Comments                              |
|-----------------------+-------------------+---------------------------------------|
| ASAP Roadmap ID       | 202               | Establish Company Structure           |
| Mandatory/Optional    | Optional activity | Only needed for company consolidation |
| Critical/Non-Critical | Non-Critical      |                                       |

** Create Consolidation Entity                                         
In this Customizing activity, you define consolidation entities. An entity could be a company, a profit center, or a cost center. The meta of Consolidation entity is defined in the consoldiation dimension.

| Attribute             | Value              | Comments                    |
|-----------------------+--------------------+-----------------------------|
| ASAP Roadmap ID       | 202                | Establish Company Structure |
| Mandatory/Optional    | Mandatory activity |                             |
| Critical/Non-Critical | Critical           |                             |

*** Manually Create Consolidation Entities
You can manually create consolidation entities in this maintenance view. You must first choose a Consolidation dimension, and then maintain your entities. You should also maintain BPC requried attributes for each entity. 

You can write an ABAP report to generate entities automatically based on your existing master data. 
SAP recormands you first use "RTC_AUTO_PUMP_ENTITIES" to generate your entities, then use this Maintenance view to do adjustments. 

*TCode*: RTCENT

*Maintenance View*: VC_RTC_MODEL_DIM

*** (Text Node)Generate Consolidation Entities Automatically
=Use=
You can use report "RTC_AUTO_PUMP_ENTITIES" to generate consolidation entities based on existing master data. Select one consolidation dimension and press execute, the report will create all entities based on your existing master data. 

=Prerequiste=
You have your corresponding master data defined, like company, profit center, cost center, and so on. 

=Activity=
1. Run report "RTC_AUTO_PUMP_ENTITIES" using SA38. 
2. Select a pre-delivered dimension (100 or 500)
3. Press Execute 

=Notes=
*You can only use this report to generate entites based on SAP pre-delivered consolidation dimensions.* For your self-defined dimensions, it is good to write an ABAP report to do your entities auto-generation. You can refer ABAP report "RTC_AUTO_PUMP_ENTITIES".

** Define Version Related Fields
Version related fields are characteristic fields which are combined together to form a consolidation version. A consolidation version reflects a consolidation purpose. From technique point of view, each version related field must be in ACDOCC, and it must be a characteristic field. 

Currently, you can define 3 version related fields: 
1. RTC Data Category
2. Consolidation Ledger
3. Variant

Developer: Chen, Lynn <lynn.chen02@sap.com>

*** RTC Data Category
Used to isolate the consolidation result data set for deferent purpose. Like "Actual", "Plan", "Simulation".

*TCode*: RTCCAT

*Maintenance View*: V_RTC_DCATEG

| Attribute             | Value              | Comments              |
|-----------------------+--------------------+-----------------------|
| ASAP Roadmap ID       | 203                | Establish Master Data |
| Mandatory/Optional    | Mandatory activity |                       |
| Critical/Non-Critical | Critical           |                       |

*** Consolidation Ledger
Consolidation Ledger is seperate ledger with G/L accounting ledger.

A consolidation ledger can map to one or more operational ledgers. 

*TCode*: RTCLM

*Maintenance View*: VC_RTC_LEDGER

| Attribute             | Value              | Comments              |
|-----------------------+--------------------+-----------------------|
| ASAP Roadmap ID       | 203                | Establish Master Data |
| Mandatory/Optional    | Mandatory activity |                       |
| Critical/Non-Critical | Critical           |                       |

*** Variant
Under the combination of "RTC Data Category" and "Consolidation Ledger", you may want to further differentiate the consolidation result set. For example, "Actual / 1L / 100" for legal disclosure, and "Actual / 1L / 200" for internal management reporting. 

*TCode*: RTCVER

*Maintenance View*: V_RTC_VERSION

| Attribute             | Value              | Comments              |
|-----------------------+--------------------+-----------------------|
| ASAP Roadmap ID       | 203                | Establish Master Data |
| Mandatory/Optional    | Mandatory activity |                       |
| Critical/Non-Critical | Critical           |                       |

** Define Consolidation Model.
=Use=
Consolidation model combines all related customization together into an integral consolidation context. It mainly contains 2 parts: S/4 RTC side, and BPC side.

You must first generate =Consolidation Views= in RTC side. Consolidation views are generated based on the foundation view and the consolidation journal table ACDOCC. There are 2 categories of consolidation views:
1. Consolidation views for BPC which are HANA calculation views.
2. Consolidation views for RTC which are CDS views.

With the generated BPC consolidation views, you use a BW composite provider to union them. With this composite provider you can do BPC model definition. More details on how to define BPC consolidation model can be found in section "BPC Integration".

After you successfully define your BPC model, you come back here to do additional settings:
1. Assign BPC environment and model name.
2. Define BPC data categories, and mapping them to RTC version fields combinations.
3. Assign currency translation method if "Currency Translation in S4H" is checked. 
4. Do checks and validations, if all settings are correct, then you can activate the consolidation model.

*TCode*: RTCMD

*SOBJ*: RTCA

| Attribute             | Value              | Comments                       |
|-----------------------+--------------------+--------------------------------|
| ASAP Roadmap ID       | 105                | Define functions and processes |
| Mandatory/Optional    | Mandatory activity |                                |
| Critical/Non-Critical | Critical           |                                |

~This node and its sub-nodes can be all defined as text nodes.~

Developer: Sam Sun (sam.sun03@sap.com)

=Activities=
1. You enter a model name with 6 char long, and click the button "New". In the pop-up dialog screen, you can assign the foundation view. Click "OK" will generate a consolidation area view for you. You can then use the consolidation area view to define your HANA calculation view and BW composite info-provider.
2. In the tab-strip "Integration", you can assign a BPC environment name and a model name. The combination must be exist in BPC side. It will then read all the settings at BPC side, like: dimension field, fiscal year variant, chart of accounts, and so on. You just needn't do these settings again in RTC side.  If "Currency Translation in S4H" is checked, you then assign a currency translation method. 
3. BPC Category represents the versions or scenarios based on which data would be tracked. It contains the types of data you are going to track, such as Actual, Budget, and Forecast. You can set up categories to store versions, such as BudgetV1, BudgetV2, and so on.
4. In the tab-strip "Version", you can add/delete a "BPC Data Category". When you add one, it must be a unique "BPC Data Category". You then choose each version field a value, the value combination should be unique too.

** Define Account Selection
Not all the operational accounts need to be involved in consolidation. These operational accounts should be filtered out. You can achieve this through defining G/L Account Selection("&SELECTION001").

The G/L Account Selection is generated at the first time you enter it. You can change it, activate it, but not delete it. You include multiple single selections into G/L Account Selection to form the filtering logic of different chart of accounts. Each single selection is connected with operator 'or'. 

=Example=
You want account numbers "1000000"~"9000000" in chart of account "CACN" to be involved in consolidation, you also want account numbers "100000"~"999999" in chart of account "CAUS" to be involved in consolidation. Then you define 2 single selections for "CACN" and "CAUS", and add them into the G/L Account Selection. 

~Selections with their name begin with "&" are reserved by SAP for internal usages. You can not create/delete selections begin with "&". But you change/activate them.~ 

For details on how to define selections, please refer the "Define Selection" section.

*TCode*: RTCAS

*SOBJ*:  RTCA

| Attribute             | Value             | Comments                |
|-----------------------+-------------------+-------------------------|
| ASAP Roadmap ID       | 152               | Define data acquisition |
| Mandatory/Optional    | Optional activity |                         |
| Critical/Non-Critical | Non-Critical      |                         |

** Define Consolidation Document type
You define consolidation document type to differentiate types of consolidation documents generated by different consolidation tasks. In a document type, you maintain different number range intervals for different consolidation versions. You can also set whether the document type need to do balance check or not?

Before defining document types, you must first have your model defined. As document types are belong to a model, and cannot be shared among different models. 

| Attribute             | Value              | Comments                       |
|-----------------------+--------------------+--------------------------------|
| ASAP Roadmap ID       | 105                | Define functions and processes |
| Mandatory/Optional    | Mandatory activity |                                |
| Critical/Non-Critical | Critical           |                                |

Developer: Zhou, Kaiyuan <kaiyuan.zhou@sap.com>

*** Define Number Range Intervals
You define different number range intervals for a given model. 

*TCode*: RTCNR

| Attribute             | Value              | Comments            |
|-----------------------+--------------------+---------------------|
| ASAP Roadmap ID       | 250                | Define Number Range |
| Mandatory/Optional    | Mandatory activity |                     |
| Critical/Non-Critical | Critical           |                     |

*** Maintain Document Types
A document type categories documents by combining configurations like: balance check or not, manually post or automatically post. Besides, you also need to assign 2 main objects to a document type:
1. You assign number range for each consolidation version under the model.
2. You assign selected accounts (FS items) for unbalance amount to be recorded.

*TCode*: RTCDT

*SOBJ*: RTCA

** (Text Node) Define Consolidation Group
You go to BPC's web console, choose your consolidation environment, goto Administration-->Dimensions, select your group dimension (/ERP/GROUP by default). You maintain your consolidation group hierarchy.

You then goto Consolidation-->Ownership Manager, choose the category, group, and Fiscal Year/Period. You can then add your consolidation entities under each group node.

The consolidation hierarchy defined in BPC can be accessed in RTC for its currency translation (if "Currency Translation in RTC" is set). Only the hierarchy structure and group currency information is used, other like "Consolidation Method", "Percent Consolidation", "Percent Control", and "Percent Ownership" is only relevant for BPC.  

| Attribute             | Value              | Comments                    |
|-----------------------+--------------------+-----------------------------|
| ASAP Roadmap ID       | 202                | Establish Company Structure |
| Mandatory/Optional    | Mandatory activity |                             |
| Critical/Non-Critical | Critical           |                             |


* Currency Translation
You define translation methods under a consolidation model. You can define multiple translation methods for a model, however, you can only have one working translation method for each model. 

| Attribute             | Value             | Comments                        |
|-----------------------+-------------------+---------------------------------|
| ASAP Roadmap ID       | 105               | Define Functions                |
| Mandatory/Optional    | Optional activity | Only needed if CT is in S/4HANA |
| Critical/Non-Critical | Critical          |                                 |

| Developer                            | Responsible Part       |
|--------------------------------------+------------------------|
| Chang Liu <chang.liu03@sap.com>      | Customization UI       |
| Qian, Marvin <marvin.qian@sap.com>   | Translation Algorithms |
| Mo, Steve <steve.mo@sap.com>         | APIs                   |
| Zhang, Vinent<vincent.zhang@sap.com> | Selection              |

** Define Selection
You can use =Selection= to further filter data on a consolidation view. 

Selection is a model depandent object. You can add filter conditions on the fields of a consolidation view. The filter conditions are then compiled into a SQL where-expression, which can be applied during the running of consolidation tasks. 

The filter conditions could be either based on SETs, or directly input select-options, or the freely entered where-expressions. And you can combine multiple selections into a composite selection to form a more complex filter option.

*TCode*: RTCSEL

*SOBJ*:  RTCA

| Attribute             | Value              | Comments                          |
|-----------------------+--------------------+-----------------------------------|
| ASAP Roadmap ID       | 152                | Define data acquisition           |
| Mandatory/Optional    | Mandatory activity | You must define selections for CT |
| Critical/Non-Critical | Non-Critical       |                                   |

*** (Text Node)Reuse SETs 
If you already have your G/L accounting and subitem SETs, then you can re-use SETs as selection. Create selections with type "1" (based on SETs).

| Attribute             | Value             | Comments                          |
|-----------------------+-------------------+-----------------------------------|
| ASAP Roadmap ID       | 152               | Define data acquisition           |
| Mandatory/Optional    | Optional activity | You must define selections for CT |
| Critical/Non-Critical | Non-Critical      |                                   |

** Exchange Rate Indicater
You maintain an exchange rate indicater and map it an exchange rate type. 

| Attribute             | Value              | Comments              |
|-----------------------+--------------------+-----------------------|
| ASAP Roadmap ID       | 203                | Establish Master Data |
| Mandatory/Optional    | Mandatory activity |                       |
| Critical/Non-Critical | Critical           |                       |

*TCode*: RTCER

*SOBJ*:  RTCA

*** Check Exchange Rate Type
~Copy Node: SAP Netweaver-->General settings-->Currencies-->Check Exhange Rate Types~

** Define Currency Translation Methods
A translation method includes translation entries and rounding entries. Based on the defination, an ABAP class contains AMDP methods will be created. At runtime, the system will call the generated AMDP-methods, so that all the translation logics are pushed down to HANA.  

Translation method is model depandent. You can define multiple translation methods for a consolidation model, but only one method is the working one. 

In the translation method header, you need to assign:
1. A document type for automatic posting during transaltion run.
2. A reference exchange rate type.

You then add one or more translation entries. On each entry, you add a =selection= to boundary data by  accounts and its subitems. You then assign an exchange rate type and a currency translation key. A currecny translation key is mapping to a translation algorithm(for details, see "Define Translation Key"). In the amount area, you can choose which amount field is used as the source amount. The traget amount is always fixed to "CONS_SL".  

For the differential amounts, you can assign a differential account and its subitems to record them. 

If rounding needs to be processed, you can add rounding entries in the "Rounding" tab. Unlike translation entries, rounding entries has sequence depandancy. During runtime, the rounding entries are excuted up to down.

*TCode*: RTCTM

*SOBJ*:  RTCA

| Attribute             | Value              | Comments              |
|-----------------------+--------------------+-----------------------|
| ASAP Roadmap ID       | 204                | Establish Functions   |
| Mandatory/Optional    | Mandatory activity | Main CT customization |
| Critical/Non-Critical | Non-Critical       |                       |

** Define Translation Key
A translation key is mapping to a translation algorithm. Here user can define his own translation algorithm using AMDP method, and assign it with a translation key in its own namespace. 

SAP delivers 8 standard translation keys in a seperate namespace. 

A maintenance view of the mapping between translation key and the algorithm should be maintained.

*TCode*: RTCCTK

*Maintenance View*: V_RTC_CT_CTRKY 

| Attribute             | Value             | Comments           |
|-----------------------+-------------------+--------------------|
| ASAP Roadmap ID       | 151               | Define enhancement |
| Mandatory/Optional    | Optional activity |                    |
| Critical/Non-Critical | Non-Critical      |                    |


* BPC Integration
Here describe the details steps you should do for the integration with BPC. 

From BPC's perspective(embedded model), you do data preparation work for BPC consolidation modeling, you will need to provider at least three info-Providers with Aggregation Level for different purpose: Fact table data, Ownership data and Rate data.

For each Aggregation Level you expose all BPC needed dimensions(Account - A, Category - C, Audit - D, Entity - E, Group - G, Inter-company I, Currency - R, Subtables(Flow) - S), and all other user-defined dimensions( provider need these values for write back mapping, BPC will not use/ change them) 

Only one write back channel existing in these Aggregation Level, it can be Real-time cube, ADSO or Virtual Provider, and also you need a datasource like HANA view from the raw data. So generally you need one Composite Provider to union all these parts together especially for fact data info-Provider.

In order to form an info-Provider, a set of predefined info-Object should be ready. And for BPC special attribute mapping use, standard operational dimension info-Objects are not enough for BPC integration, so comes the [[https://wiki.wdf.sap.corp/wiki/display/ERPFINDEV/Masterdata+Attributes+Extension+for+Consolidation][Master data Attributes Extension for Consolidation]]

| Attribute             | Value              | Comments                      |
|-----------------------+--------------------+-------------------------------|
| ASAP Roadmap ID       | 105                | Define function and processes |
| Mandatory/Optional    | Mandatory activity |                               |
| Critical/Non-Critical | Critical           |                               |

Develper: Wu, William <william.wu02@sap.com>

** BPC Extended Property Maintenance
Since several ENTITY/ACCOUNT Master data need to be extended for BPC use, You need to maintain the following attributes for the BPC integration beside the original operational master data customization/ maintenance :

| Attribute             | Value             | Comments              |
|-----------------------+-------------------+-----------------------|
| ASAP Roadmap ID       | 203               | Establish Master Data |
| Mandatory/Optional    | Optional activity |                       |
| Critical/Non-Critical | Critical          |                       |
~All the sub-nodes share the same attributes~

Developer: Wang, Blangero <blangero.wang@sap.com>

*** +Extend Company Properties for BPC+
You should define a "Company" first. SPRO: Enterprise Structure -> Definition -> Financial Accounting -> Define company

Maintenance View: V_RTC_EXT_T880

*** +Extend Profit Center for BPC+
You should define a "Profit Center" first. SPRO: Enterprise Structure -> Definition -> Financial Accounting -> Define Profit Center

Maintenance View: V_RTC_EXT_CEPC

*** +Extend Cost Center Properties for BPC+
You should define a "Cost Center" first. SPRO: Enterprise Structure -> Definition -> Financial Accounting -> Define Profit Center

Maintenance View: V_RTC_EXT_CSKS

*** +Extend Segment Properties for BPC+
You should define a "Segment" first.  SPRO: Enterprise Structure -> Definition -> Financial Accounting -> Define Segment

Maintenance View: V_RTC_EXT_SEGM

*** +Extend Business Area Properties for BPC+
You should define a "Business Area" first. SPRO: Enterprise Structure -> Definition -> Financial Accounting -> Define Business Area

Maintenance View: V_RTC_EXT_TGSBK

*** Extend GL Account Properties for BPC:
You must have you G/L accounts created using FSP0.

*TCode*: RTCGLA

*Maintenance View*: V_RTC_EXT_SKA1

*** Extend Transaction Type for BPC:
Transaction type is mapped to BPC's flow type. So some properties should be mapped.

*TCode*: RTCTTP

*Maintenance View*: V_RTC_EXT_T856

*** Extend IBPF's Data Category for BPC:
IBPF already has its data category maintenance view. As it is the same concept for data category in planning and consolidation, it is good to have the IBPC's data category extended for the additional consolidation properties. 

*TCode*: RTCBCT

*Maintenance View*: FCOMV_CATEGORY_C

** (Text Node) Create Master Data HANA Calculation Views
In this Customizing activity, you create SAP HANA calculation views and BW info-objects for master data

By default, SAP has delivered following standard master data HANA calculation views for your reference. They are all under HANA package: sap.erp.sfin.rtc

Developer: Wang, Blangero <blangero.wang@sap.com>

| Calc View             | Description                     |
|-----------------------+---------------------------------|
| RTC_BUSINESSAREA_T880 | Attribute View of Business Area |
| RTC_COSTCENTER_CSKS   | Attribute View of Cost Center   |
| RTC_PROFITCENTER_CEPC | Attribute View of Profit Center |
| RTC_SEGMENT_SEGM      | Attribute View of Segment       |

| Attribute             | Value              | Comments                |
|-----------------------+--------------------+-------------------------|
| ASAP Roadmap ID       | 152                | Design Data acquisition |
| Mandatory/Optional    | Mandatory activity |                         |
| Critical/Non-Critical | Critical           |                         |

You create virtual InfoObjects to map to the master data SAP HANA calculation views. You then create a composite provider to union the fact SAP HANA calculation views generated by RTC modeling tool. 

You also create a virtual infoProvider on the result consolidation view. On this virtual infoProvider, you also assign a write-back class so that BPC can write-back the consoldiation reuslt to ACDOCC. 

Following BW info-objects are delivered by SAP as they are either mandatory dimensions for BPC or necessary attributes. You can active them to use. 
| Tech.name      | Description                 |
|----------------+-----------------------------|
| /ERP/DIMLIST   | BPC Dimlist                 |
| /ERP/ENA_JNR   | BPC EnableJNR               |
| /ERP/CTRL_CNL  | BPC Control currency not LC |
| /ERP/CTRL_LVL  | BPC Control level           |
| /ERP/ELIM      | BPC Elim                    |
| /ERP/FX_TYPE   | BPC Fx type                 |
| /ERP/GLAGR     | BPC Account Type            |
| /ERP/ELIMACC   | BPC ElimAcc                 |
| /ERP/TYPELIM   | BPC TypeElim                |
| /ERP/EX_RATE1  | BPC Exchange Rate Type      |
| /ERP/FXDIFFOL  | BPC Fx Difference Only      |
| /ERP/FXSCATG   | BPC Fx Source Category      |
| /ERP/DSUBMIT   | BPC Data Submit             |
| /ERP/OPECATG   | BPC Opening Category        |
| /ERP/OPEPER    | BPC Opening Period          |
| /ERP/OPEYEAR   | BPC Opening Year            |
| /ERP/OWNCATG   | BPC Own Category            |
| /ERP/OWNPER    | BPC Own Period              |
| /ERP/OWNYEAR   | BPC Own Year                |
| /ERP/RATECATG  | BPC Rate Category           |
| /ERP/RATEPER   | BPC Rate Period             |
| /ERP/RATEYEAR  | BPC Rate Year               |
| /ERP/FLOWTP    | BPC Flow Type               |
| /ERP/CPOPEN    | BPC Copy Opening            |
| /ERP/DSTYPE    | BPC DS Type                 |
| /ERP/ISCONS    | BPC Is Consolidated         |
| /ERP/ISCONV    | BPC Is Converted            |
| /ERP/OPENDS    | BPC Opening Datasource      |
| /ERP/DSSTAGE   | BPC Datasource Stage        |
| /ERP/ICORGI    | BPC IC ORIGIN               |
| /ERP/CONSTP    | BPC Consolidate Type        |
| /ERP/CURRTP    | BPC Currency Type           |
| /ERP/PARGROUP  | BPC Parent Group            |
| /ERP/STOREGCUR | BPC Store Group Currency    |
| /ERP/DSLVL     | BPC Datasource Level        |
| /ERP/STAGEOL   | BPC Stage Only              |
| /ERP/STENTITY  | BPC Store Entity            |
| /ERP/REPORTIN  | BPC Reporting               |
| /ERP/MD        | BPC MD                      |
| /ERP/FLOW      | RTC FLOW                    |
| /ERP/AUDIT     | RTC Audit                   |
| /ERP/GROUP     | RTC Group                   |
| /ERP/ECOMP     | RTC Entity Company          |
| /ERP/ICOMP     | RTC InterCompany Company    |
| /ERP/BPCCURR   | RTC Currency                |

| Attribute             | Value              | Comments                |
|-----------------------+--------------------+-------------------------|
| ASAP Roadmap ID       | 152                | Design Data acquisition |
| Mandatory/Optional    | Mandatory activity |                         |
| Critical/Non-Critical | Critical           |                         |

Developer: Wang, Blangero <blangero.wang@sap.com>

** (Text Node) Write-back to S/4
If you want to write-back the consolidated results to S/4, then you have to use an ABAP write-back class and a BW virtual provider.

SAP has delivered following objects for your reference:
| ABAP Objects                 | Description                                                |
|------------------------------+------------------------------------------------------------|
| CL_RTC_ACDOCC_IPROV_WRITABLE | Write-back class to post consolidation journals to  ACDOCC |
| +/ERP/RTC_VP01+              | +BW Virtual Provider+                                      |

| Attribute             | Value              | Comments         |
|-----------------------+--------------------+------------------|
| ASAP Roadmap ID       | 151                | Design Interface |
| Mandatory/Optional    | Mandatory activity |                  |
| Critical/Non-Critical | Critical           |                  |
 
*** Assign Document Types
You already have document types defined under the model you created. When BPC write-back the consolidted results, the document types are auto-determined by following 4 fields: Flow Type, Audit Trail, Account, and Category. You must define the derivation rules here so that correct document types are chosen for different sets of data. 

Maintenance view is under development.  

~It is also possible that BPC enhance their rules framework, so that document type can be determined at BPC's side. We will see if BPC colleagues can finish this feature on time.~

Developer: Summer Xia (summer.xia03@sap.com)

*TCode*: RTCWB

*Maintenance View*: V_RTC_MODWB

| Attribute             | Value              | Comments            |
|-----------------------+--------------------+---------------------|
| ASAP Roadmap ID       | 204                | Establish Functions |
| Mandatory/Optional    | Mandatory activity |                     |
| Critical/Non-Critical | Critical           |                     |


* +Business Add-ins+

** BAdi for Core Posing API
The "Core posting API" is developed using AMDP(ABAP Managed DB Procedure). All the up-level applications will call the core posting API to save data into ACDOCC. You can define your BAdi implementation for core posting API if you have extend fields of ACDOCC and you want additional logic to be applied on this new fields.  

Developer: Chen, Lynn <lynn.chen02@sap.com>


* Remarks

Maintain IMG: T-code SIMGH

IMG Structure: Real-Time Consolidation 
