#+PAGEID: 1825545337
#+VERSION: 23
#+STARTUP: align
#+OPTIONS: toc:1
#+TITLE: IMG Design

* Consolidation Model
Here you define consolidation related master data and basic customizations.

** (Text Node) Create Consolidation Foundation View
You need to create a HANA calculation view in HANA Studio. The calculation view is mainly based on ACDOCA, and used to
1. Project consolidastion relevent fields from ACDOCA;
2. Join group Chart of Accounts;
3. Do fiscal year variant alignment;
4. Do necessary data filtering on company code and ledger combinations.

SAP also delivers an example consolidation foundation view: *RTC_C_ACDOCA*, you can copy it to your own namespace and adjust it to your own needs. 

Developer: Zhou, Kaiyuan <kaiyuan.zhou@sap.com>

** Define a Group Chart of Accounts
Reuse existing Chart of Accounts and G/L Accounting master data maintenance. 

Financial Accounting (New)-->General Ledger Accounting (New) -->Mater Data-->G/L Accounts

** Mapping Operational Chart of Accounts to Group Chart of Accounts
When create a local G/L account, assign the corresponding group account number. The underlying DB field is SKA1-BILKT

If time permits, RTC should develop a mapping application. You can do mapping like this:
| Local CoA | Local Account   | Group CoA | Group Account |
|-----------+-----------------+-----------+---------------|
| CACN      | 1001*           | CORP      |       1002000 |
| CAJP      | 2004001         | CORP      |       2004100 |
| CAGM      | 3003001,3003002 | CORP      |       3003000 |
| CAGM      | 4004001-4005999 | CORP      |       4004000 |

** Define Account Selection
Not all the operational accounts need to be involved in consolidation. These operational accounts should be filtered out. You can achieve this through defining a special composite selection "&SELECTION001".

~Selections with their name begin with "&" are reserved by SAP for internal usages.~ 

For details on how to define selections, please refer the "Define Selection" section.

** Mapping Company Code to Company
** Define Group Fiscal Year Variants
Reuse existing Fiscal Year Variants IMG nodes: Financial Accounting (New)-->Ledgers-->Fiscal Year and Posting Periods

** Generate Fiscal Year Calendar
~Accounting team has a program to generate period level or day level granularity fiscal calendar. Maybe it is already existing in the IMG structure somewhere. But anyway we can create this node in our IMG structure. The program is: FINS_GENERATE_FISCAL_PERIOD.~ 

Developer: Zhou, Kaiyuan <kaiyuan.zhou@sap.com>

** Define Version Related Fields
Version related fields are characteristic fields which are combined together to form a consolidation version. A consolidation version reflects a consolidation purpose. From technique point of view, each version related field must be in ACDOCC, and it must be a characteristic field. 

Currently, you can define 3 version related fields: 
1. RTC Data Category
2. Consolidation Ledger
3. Variant

Developer: Chen, Lynn <lynn.chen02@sap.com>

*** RTC Data Category
Used to isolate the consolidation result data set for deferent purpose. Like "Actual", "Plan", "Simulation".

Maintenance View: under development

*** Consolidation Ledger
A consolidation ledger can map to an accounting principle (US GAAP, IFRS, and so on). Ledger is useful when, for example, data in an extend ledger "1L" combined with the data in leading ledger "0L" can form a union data set to fulfill a specific accounting principle. Thus can reduce the data redundancy. 

Maintenance View: under development

*** Variant
Under the combination of "RTC Data Category" and "Consolidation Ledger", you may want to further differentiate the consolidation result set. For example, "Actual / 1L / 100" for legal disclosure, and "Actual / 1L / 200" for internal management reporting. 

Maintenance View: V_RTC_VERSION

** Define Consolidation Model.

Consolidation model combines all related customization together into an integral consolidation context. It mainly contains 2 parts: S/4 RTC side, and BPC side.

You must first generate =Consolidation Views= in RTC side. Consolidation views are generated based on the foundation view and the consolidation journal table ACDOCC. There are 2 categories of consolidation views:
1. Consolidation views for BPC which are HANA calculation views.
2. Consolidation views for RTC which are CDS views.

With the generated BPC consolidation views, you use a BW composite provider to union them. With this composite provider you can do BPC model definition. More details on how to define BPC consolidation model can be found in section "BPC Integration".

After you successfully define your BPC model, you come back here to do additional settings:
1. Assign BPC environment and model name.
2. Define BPC data categories, and mapping them to RTC version fields combinations.
3. Assign currency translation method if "Currency Translation in S4H" is checked. 
4. Do checks and validations, if all settings are correct, then you can activate the consolidation model.

Developer: Sam Sun (sam.sun03@sap.com)

*** Create a RTC Consolidation Model
You enter a model name with 6 char long, and click the button "New". In the pop-up dialog screen, you can assign the foundation view. Click "OK" will generate a consolidation area view for you. You can then use the consolidation area view to define your HANA calculation view and BW composite info-provider.

The Tcode "RTCMODEL" is still under development.

*** Assign BPC Environment and Model Name
In the tab-strip "Integration", you can assign a BPC environment name and a model name. The combination must be exist in BPC side. It will then read all the settings at BPC side, like: dimension field, fiscal year variant, chart of accounts, and so on. You just needn't do these settings again in RTC side.  

If "Currency Translation in S4H" is checked, you then assign a currency translation method. 

*** Define BPC Data Category and Map it to RTC Version Fields Combination
In the tab-strip "Version", you can add/delete a "BPC Data Category". When you add one, it must be a unique "BPC Data Category". You then choose each version field a value, the value combination should be unique too.

** Define Consolidation Document type
You define consolidation document type to differentiate types of consolidation documents generated by different consolidation tasks. In a document type, you maintain different number range intervals for different consolidation versions. You can also set whether the document type need to do balance check or not?

Before defining document types, you must first have your model defined. As document types are belong to a model, and cannot be shared among different models. 

Developer: Zhou, Kaiyuan <kaiyuan.zhou@sap.com>

*** Define Number Ranges
You define different number range intervals for a given model. 

*** Maintain Document Types
A document type categories documents by combining configurations like: balance check or not, manually post or automatically post. Besides, you also need to assign 2 main objects to a document type:
1. You assign number range for each consolidation version under the model.
2. You assign selected accounts (FS items) for unbalance amount to be recorded.

** (Text Node) Define Consolidation Group and Unit
You go to BPC's web console, choose your consolidation environment, goto Administration-->Dimensions, select your group dimension (/ERP/GROUP by default). You maintain your consolidation group hierarchy.

You then goto Consolidation-->Ownership Manager, choose the category, group, and Fiscal Year/Period. You can then add your consolidation entities under each group node.

The consolidation hierarchy defined in BPC can be accessed in RTC for its currency translation (if "Currency Translation in RTC" is set). Only the hierarchy structure and group currency information is used, other like "Consolidation Method", "Percent Consolidation", "Percent Control", and "Percent Ownership" is only relevant for BPC.  


* Currency Translation
You define translation methods under a consolidation model. You can define multiple translation methods for a model, however, you can only have one working translation method for each model. 

| Developer                          | Responsible Part       |
|------------------------------------+------------------------|
| Chang Liu (chang.liu03@sap.com)    | Customization UI       |
| Qian, Marvin <marvin.qian@sap.com> | Translation Algorithms |
| Mo, Steve <steve.mo@sap.com>       | APIs                   |

** Define SETs (Optional)
You use GS01/GS02/GS03 to Create/Edit/Display a SET.

*** Account SET
You create a SET for GL accounts.

*** Subitem SET
You create a subitem SET. Subitems are characteristic fields in ACDOCA/C which are used to further category accounts. 

** Define Selection
You can use =Selection= to further filter data on a consolidation view. 

Selection is a model depandent object. You can add filter conditions on the fields of a consolidation view. The filter conditions are then compiled into a SQL where-expression, which can be applied during the running of consolidation tasks. 

The filter conditions could be either based on SETs, or directly input select-options, or the freely entered where-expressions. And you can combine multiple selections into a composite selection to form a more complex filter option.

The Tcode is "RTCSEL".

** Exchange Rate Indicator
A mapping with exchange rate type.

The Tcode "RTCERI" is done.


** Define Currency Translation Methods
A translation method includes translation entries and rounding entries. Based on the defination, an ABAP class contains AMDP methods will be created. At runtime, the system will call the generated AMDP-methods, so that all the translation logics are pushed down to HANA.  

Translation method is model depandent. You can define multiple translation methods for a consolidation model, but only one method is the working one. 

In the translation method header, you need to assign a reference exchange rate indicator and a document type to a trans

*** Create Translation Method
You need to 
The Tcode "RTCTM" is under development.

*** Add Translation Entries
Translation entry combines a =Selection=, an exchange rate indicator, a translation key which points a translation algorithm, and a pair of differential items with their subitems.

The Tcode "RTCTE" is under development.

*** Add Rounding Rounding Entries 
Contains 1 or 2 =Selections= to do rounding check and rounding difference processing. 

The Tcode "RTCRE" is under development.


** Define Translation Key
A translation key is mapping to a translation algorithm. Here user can define his own translation algorithm using AMDP method, and assign it with a translation key in its own namespace. 

SAP delivers 8 standard translation keys. 

A maintenance view of the mapping between translation key and the algorithm should be maintained.


* BPC Integration
Here describe the details steps you should do for the integration with BPC. 

From BPC's perspective(embedded model), you do data preparation work for BPC consolidation modeling, you will need to provider at least three info-Providers with Aggregation Level for different purpose: Fact table data, Ownership data and Rate data.

For each Aggregation Level you expose all BPC needed dimensions(Account - A, Category - C, Audit - D, Entity - E, Group - G, Inter-company I, Currency - R, Subtables(Flow) - S), and all other user-defined dimensions( provider need these values for write back mapping, BPC will not use/ change them) 

Only one write back channel existing in these Aggregation Level, it can be Real-time cube, ADSO or Virtual Provider, and also you need a datasource like HANA view from the raw data. So generally you need one Composite Provider to union all these parts together especially for fact data info-Provider.

In order to form an info-Provider, a set of predefined info-Object should be ready. And for BPC special attribute mapping use, standard operational dimension info-Objects are not enough for BPC integration, so comes the [[https://wiki.wdf.sap.corp/wiki/display/ERPFINDEV/Masterdata+Attributes+Extension+for+Consolidation][Master data Attributes Extension for Consolidation]]

Develper: Wu, William <william.wu02@sap.com>

** BPC Extent Property Maintenance
Since several ENTITY/ACCOUNT Master data need to be extended for BPC use, You need to maintain the following attributes for the BPC integration beside the original operational master data customization/ maintenance :

Developer: Wang, Blangero <blangero.wang@sap.com>

*** Extend Company Properties for BPC:
You should define a "Company" first. SPRO: Enterprise Structure -> Definition -> Financial Accounting -> Define company

Maintenance View: V_RTC_EXT_T880

*** Extend Profit Center for BPC:
You should define a "Profit Center" first. SPRO: Enterprise Structure -> Definition -> Financial Accounting -> Define Profit Center

Maintenance View: V_RTC_EXT_CEPC

*** Extend Cost Center Properties for BPC:
You should define a "Cost Center" first. SPRO: Enterprise Structure -> Definition -> Financial Accounting -> Define Profit Center

Maintenance View: V_RTC_EXT_CSKS

*** Extend Segment Properties for BPC:
You should define a "Segment" first.  SPRO: Enterprise Structure -> Definition -> Financial Accounting -> Define Segment

Maintenance View: V_RTC_EXT_SEGM

*** Extend Business Area Properties for BPC:
You should define a "Business Area" first. SPRO: Enterprise Structure -> Definition -> Financial Accounting -> Define Business Area

Maintenance View: V_RTC_EXT_TGSBK

*** Extend GL Account Properties for BPC:
You must have you G/L accounts created using FSP0.

Maintenance View: V_RTC_EXT_SKA1


** (Text Node) Create HANA Calculation Views
You create a FACT HANA calculation view based the consolidation area view that are generated during RTC modeling. You should also create master data HANA views to expose you master data. 

By default, SAP has delivered following standard master data HANA calculation views for your reference. They are all under HANA package: sap.erp.sfin.rtc

Developer: Wang, Blangero <blangero.wang@sap.com>

| Calc View             | Description                                           |
|-----------------------+-------------------------------------------------------|
| RTC_C_ACDOCA          | Fact View based on ACDOCA                             |
| RTC_C_SCOMPL          | Fact View based on the cons area view of model SCOMPL |
| RTC_BUSINESSAREA_T880 | Attribute View of Business Area                       |
| RTC_COSTCENTER_CSKS   | Attribute View of Cost Center                         |
| RTC_PROFITCENTER_CEPC | Attribute View of Profit Center                       |
| RTC_SEGMENT_SEGM      | Attribute View of Segment                             |

** (Text Node) Create BW Info-objects and Info-Provider
You need to create virtual info-objects to mapping the master data HANA views. You then create a real-time cube with the same fields of the FACT HANA calculation view. Then union the Real-time cube with the fact view through a composite provider.

*We wont deliver these BW objects.* 
+SAP has delivered following BW contents for your reference:+
| BW Objects      | Description                                |
|-----------------+--------------------------------------------|
| +/ERP/RTC_RT01+ | +Real-time cube according to RTC_C_ACDOCA+ |
| +/ERP/RTC_CP01+ | +Composite Provider on RTC_C_ACDOCA+       |
| +/ERP/RTC_AL01+ | +Aggregation Level on /ERP/RTC_CP01+       |
| +/ERP/RTC_RT02+ | +Real-time cube according to RTC_C_SCOMPL+ |
| +/ERP/RTC_CP02+ | +Composite Provider on RTC_C_SCOMPL+       |
| +/ERP/RTC_AL02+ | +Aggregation Level on /ERP/RTC_CP01+       |

Developer: Wang, Blangero <blangero.wang@sap.com>

** (Text Node) Write-back to S/4
If you want to write-back the consolidated results to S/4, then you have to use an ABAP write-back class and a BW virtual provider. 

SAP has delivered following objects for your reference:
| ABAP Objects                 | Description                                                |
|------------------------------+------------------------------------------------------------|
| CL_RTC_ACDOCC_IPROV_WRITABLE | Write-back class to post consolidation journals to  ACDOCC |
| +/ERP/RTC_VP01+              | +BW Virtual Provider+                                      |
  
*** Assign Document Types
You already have document types defined under the model you created. When BPC write-back the consolidted results, the document types are auto-determined by following 4 fields: Flow Type, Audit Trail, Account, and Category. You must define the derivation rules here so that correct document types are chosen for different sets of data. 

Maintenance view is under development.  

~It is also possible that BPC enhance their rules framework, so that document type can be determined at BPC's side. We will see if BPC colleagues can finish this feature on time.~

Developer: Summer Xia (summer.xia03@sap.com)


* Business Add-ins

** BAdi for Core Posing API
The "Core posting API" is developed using AMDP(ABAP Managed DB Procedure). All the up-level applications will call the core posting API to save data into ACDOCC. You can define your BAdi implementation for core posting API if you have extend fields of ACDOCC and you want additional logic to be applied on this new fields.  

Developer: Chen, Lynn <lynn.chen02@sap.com>
