#+PAGEID: 
#+VERSION: 1
#+STARTUP: align
#+OPTIONS: toc:1
#+TITLE: Consolidation Should Be Real-Time

* Demo Existing Fruits

** Data Release Cockpit
Control data without replication

*** Cut-off Timestamp

*** Variation Detecting

*** Embedded Financial Statement for Entities

*** Embedded Validation Result

** Validation
Validation runs in HANA

*** Pushed Down to HANA
ABAP independent
Compiled to SQL DB procedure
Run in parellel
 
*** Web-based Rule Editor
Google-like auto-completion list
Flexible and Complete

*** Drill-through to explain

** Flexible Upload
Limited functions are provided

** Data Modeling
Borrowed ideas from BCS and EC-CS.

*** Data Stream

*** Generate Cube v.s. Generate View
Cube means data replication, view means real-time. 
*** The Method Framework
Currency Translation
*** Version Concept

* Real-Time & Cloud
When I took the topic "Real-Time Consolidation", I am always thinking what does "Real-Time" mean to an analytic APP. 

** Real-Time Data
No data replication. Of course, that is the obvious differences compared with existing solutions for decades. And Real-Time Consolidation is always the target which is chased for many years. The difficulties are:

*** Where is the real-time data?
A machine gun without bullets. Accounting system plus consolidation system.

*** Concurrency Control
ACDOCA is growing, organization is changing, so does the chart-of-accounts. Then how those changes directly impact the consolidation?

*** Real-Time Transaction

** Real-Time Modeling

* Performance

* Close to Data

* Move to the Cloud 
Distribution Model

* Conclusion
Consolidation solutions are complicate, however, every successful product has a very simple core inside. The core logic can be usually concluded in one santence:
1. EC-CS: A wizard for consolidation;
2. SEM-BCS: A BW cube generator for consolidation;
3. BPC: A data replicator for consolidation;
4. RTC: A SQL generator for consolidation.

Once you get it, you can then predicate everything. That's the most wonderful product experience.   

Get rid of ABAP, share among HCP and S4HANA
